uploads = []

[[generated]]
id = "SmMHysVrgaFz-Z722HdDx"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "muzvTFOdHuNeW-udV67yZ"
uri = "file://artifacts/mobile/assets/images/onboarding1.png"
type = "image"
title = "kenyan driver speed camera app"

[[generated]]
id = "l8W_gLIuzpBDoIej9cRuV"
uri = "file://artifacts/mobile/assets/images/onboarding2.png"
type = "image"
title = "kenyan woman driving speed display"

[[generated]]
id = "-TQloc5Ot9RydRKVtJmJy"
uri = "file://artifacts/mobile/assets/images/onboarding3.png"
type = "image"
title = "kenyan drivers community sharing"

[[generated]]
id = "3kzLyDd6WLSW-GX2pqksY"
uri = "file://artifacts/mobile/assets/images/onboarding4.png"
type = "image"
title = "kenyan man location phone nairobi"

[[generated]]
id = "yf0g1tfMbDzJmeJRj2Hmu"
uri = "file://artifacts/marketing/public/images/hero-bg.png"
type = "image"
title = "Cinematic night highway from dashboard"

[[generated]]
id = "m3iyIYynN7j4qVjXzE4_Y"
uri = "file://artifacts/marketing/public/images/app-ui.png"
type = "image"
title = "Minimalist dark mode navigation map"

[[generated]]
id = "2Ay__csWsk8VtW7tnmwI3"
uri = "file://artifacts/marketing/public/images/nairobi-night.png"
type = "image"
title = "Nairobi highway at dusk"

[[outputs]]
id = "2-AYpwHxIfnZcwJt0QIuG"
uri = "file://msafiri-app-store-screenshots.zip"
type = "unspecified"
title = "Msafiri App Store Screenshots"
