import { Router, type IRouter } from "express";
import healthRouter from "./health";
import reportsRouter from "./reports";
import speedZonesRouter from "./speedZones.js";
import pushRouter from "./push.js";
import appVersionRouter from "./appVersion.js";
import blogRouter from "./blog.js";
import tripsRouter from "./trips.js";
import creatorsRouter from "./creators.js";
import adminRouter from "./admin/index.js";
import shareRouter from "./share.js";
import courseRouter from "./course.js";
import storageRouter from "./storage.js";
import placesRouter from "./places.js";
import adminMobileRouter from "./admin-mobile.js";
import routingRouter from "./routing.js";
import ttsRouter from "./tts.js";
import poisRouter from "./pois.js";
import trafficRouter from "./traffic.js";
import appSettingsRouter from "./appSettings.js";
import dashcamRouter from "./dashcam.js";
import emergencyRouter from "./emergency.js";
import telemetryRouter from "./telemetry.js";

const router: IRouter = Router();

router.use(placesRouter);
router.use(healthRouter);
router.use(reportsRouter);
router.use(speedZonesRouter);
router.use(pushRouter);
router.use(appVersionRouter);
router.use(blogRouter);
router.use(tripsRouter);
router.use(creatorsRouter);
router.use("/admin", adminRouter);
router.use(shareRouter);
router.use(courseRouter);
router.use(storageRouter);
router.use(adminMobileRouter);
router.use(routingRouter);
router.use(ttsRouter);
router.use(poisRouter);
router.use(trafficRouter);
router.use(appSettingsRouter);
router.use(dashcamRouter);
router.use(emergencyRouter);
router.use(telemetryRouter);

export default router;
