// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/VoiceSampler.tsx": () => import("../components/mockups/VoiceSampler.tsx"),
  "./components/mockups/onboarding/Slide1SpeedCameras.tsx": () => import("../components/mockups/onboarding/Slide1SpeedCameras.tsx"),
  "./components/mockups/onboarding/Slide2Navigation.tsx": () => import("../components/mockups/onboarding/Slide2Navigation.tsx"),
  "./components/mockups/onboarding/Slide3Community.tsx": () => import("../components/mockups/onboarding/Slide3Community.tsx"),
  "./components/mockups/onboarding/Slide4DriveMode.tsx": () => import("../components/mockups/onboarding/Slide4DriveMode.tsx"),
  "./components/mockups/onboarding/Slide5Vehicle.tsx": () => import("../components/mockups/onboarding/Slide5Vehicle.tsx")
};
