/**
 * backfillCourseAudio — runs at API server startup.
 *
 * Populates audio_url for any course_lessons row that is still NULL.
 * This is a one-time migration for production databases that were seeded
 * before TTS audio generation ran against the dev database.
 */

import { db } from "@workspace/db";
import { courseLessonsTable } from "@workspace/db";
import { sql } from "drizzle-orm";
import { logger } from "../lib/logger";

/** Exact slug → GCS object path mapping generated by the TTS pipeline. */
const AUDIO_URLS: Record<string, string> = {
  "foreword-foreword": "audio/foreword-foreword.mp3",
  "unit-01-introduction-to-driving-introduction-to-driving": "audio/unit-01-introduction-to-driving-introduction-to-driving.mp3",
  "unit-02-fundamental-driving-rules-fundamental-driving-rules": "audio/unit-02-fundamental-driving-rules-fundamental-driving-rules.mp3",
  "unit-03-model-town-model-town": "audio/unit-03-model-town-model-town.mp3",
  "unit-04-human-factors-in-traffic-human-factors-in-traffic": "audio/unit-04-human-factors-in-traffic-human-factors-in-traffic.mp3",
  "unit-05-vehicle-constructions-and-controls-vehicle-constructions-and-controls": "audio/unit-05-vehicle-constructions-and-controls-vehicle-construct.mp3",
  "unit-06-self-inspection-of-vehicle-self-inspection-of-vehicle": "audio/unit-06-self-inspection-of-vehicle-self-inspection-of-vehicl.mp3",
  "unit-07-observation-driver-visibility": "audio/unit-07-observation-driver-visibility.mp3",
  "unit-07-observation-exterior-mirror": "audio/unit-07-observation-exterior-mirror.mp3",
  "unit-07-observation-observation": "audio/unit-07-observation-observation.mp3",
  "unit-07-observation-rear-view-mirror-interior-mirror": "audio/unit-07-observation-rear-view-mirror-interior-mirror.mp3",
  "unit-07-observation-the-blind-spot": "audio/unit-07-observation-the-blind-spot.mp3",
  "unit-08-vehicle-control-j-turns": "audio/unit-08-vehicle-control-j-turns.mp3",
  "unit-08-vehicle-control-u-turn": "audio/unit-08-vehicle-control-u-turn.mp3",
  "unit-08-vehicle-control-vehicle-control": "audio/unit-08-vehicle-control-vehicle-control.mp3",
  "unit-09-communication-on-the-road-communication-on-the-road": "audio/unit-09-communication-on-the-road-communication-on-the-road.mp3",
  "unit-09-communication-on-the-road-signals-given-by-road-users": "audio/unit-09-communication-on-the-road-signals-given-by-road-user.mp3",
  "unit-09-communication-on-the-road-traffic-light-signals": "audio/unit-09-communication-on-the-road-traffic-light-signals.mp3",
  "unit-09-communication-on-the-road-traffic-signal-blackout": "audio/unit-09-communication-on-the-road-traffic-signal-blackout.mp3",
  "unit-10-speed-management-braking-distance": "audio/unit-10-speed-management-braking-distance.mp3",
  "unit-10-speed-management-braking-systems-and-techniques": "audio/unit-10-speed-management-braking-systems-and-techniques.mp3",
  "unit-10-speed-management-freewheeling": "audio/unit-10-speed-management-freewheeling.mp3",
  "unit-10-speed-management-how-poor-speed-management-affects-driving": "audio/unit-10-speed-management-how-poor-speed-management-affects-d.mp3",
  "unit-10-speed-management-risks-of-freewheeling": "audio/unit-10-speed-management-risks-of-freewheeling.mp3",
  "unit-10-speed-management-speed-management": "audio/unit-10-speed-management-speed-management.mp3",
  "unit-10-speed-management-stopping-distance": "audio/unit-10-speed-management-stopping-distance.mp3",
  "unit-10-speed-management-the-4-second-rule": "audio/unit-10-speed-management-the-4-second-rule.mp3",
  "unit-10-speed-management-thinking-distance": "audio/unit-10-speed-management-thinking-distance.mp3",
  "unit-11-space-management-position-to-see-and-be-seen": "audio/unit-11-space-management-position-to-see-and-be-seen.mp3",
  "unit-11-space-management-space-management": "audio/unit-11-space-management-space-management.mp3",
  "unit-11-space-management-space-recovery": "audio/unit-11-space-management-space-recovery.mp3",
  "unit-11-space-management-to-manage-space": "audio/unit-11-space-management-to-manage-space.mp3",
  "unit-12-emergency-manoeuvres-blowouts": "audio/unit-12-emergency-manoeuvres-blowouts.mp3",
  "unit-12-emergency-manoeuvres-brake-failure": "audio/unit-12-emergency-manoeuvres-brake-failure.mp3",
  "unit-12-emergency-manoeuvres-defensive-driving": "audio/unit-12-emergency-manoeuvres-defensive-driving.mp3",
  "unit-12-emergency-manoeuvres-defensive-driving-is-important-when-in-the-followin": "audio/unit-12-emergency-manoeuvres-defensive-driving-is-important-.mp3",
  "unit-12-emergency-manoeuvres-defensive-driving-techniques": "audio/unit-12-emergency-manoeuvres-defensive-driving-techniques.mp3",
  "unit-12-emergency-manoeuvres-emergency-manoeuvres": "audio/unit-12-emergency-manoeuvres-emergency-manoeuvres.mp3",
  "unit-12-emergency-manoeuvres-if-your-headlights-go-off": "audio/unit-12-emergency-manoeuvres-if-your-headlights-go-off.mp3",
  "unit-12-emergency-manoeuvres-if-your-wheel-goes-off-the-pavement": "audio/unit-12-emergency-manoeuvres-if-your-wheel-goes-off-the-pave.mp3",
  "unit-12-emergency-manoeuvres-importance-of-defensive-driving": "audio/unit-12-emergency-manoeuvres-importance-of-defensive-driving.mp3",
  "unit-12-emergency-manoeuvres-safely-performing-evasive-turns-on-the-road": "audio/unit-12-emergency-manoeuvres-safely-performing-evasive-turns.mp3",
  "unit-13-skid-control-and-recovery-aquaplaning": "audio/unit-13-skid-control-and-recovery-aquaplaning.mp3",
  "unit-13-skid-control-and-recovery-causes-of-skids": "audio/unit-13-skid-control-and-recovery-causes-of-skids.mp3",
  "unit-13-skid-control-and-recovery-skid-control-and-recovery": "audio/unit-13-skid-control-and-recovery-skid-control-and-recovery.mp3",
  "unit-13-skid-control-and-recovery-skid-recovery": "audio/unit-13-skid-control-and-recovery-skid-recovery.mp3",
  "unit-13-skid-control-and-recovery-the-front-wheel-skid": "audio/unit-13-skid-control-and-recovery-the-front-wheel-skid.mp3",
  "unit-13-skid-control-and-recovery-the-rear-wheel-skid": "audio/unit-13-skid-control-and-recovery-the-rear-wheel-skid.mp3",
  "unit-14-adverse-driving-conditions-adverse-driving-conditions": "audio/unit-14-adverse-driving-conditions-adverse-driving-condition.mp3",
  "unit-14-adverse-driving-conditions-driving-in-adverse-conditions": "audio/unit-14-adverse-driving-conditions-driving-in-adverse-condit.mp3",
  "unit-14-adverse-driving-conditions-extreme-driving-conditions": "audio/unit-14-adverse-driving-conditions-extreme-driving-condition.mp3",
  "unit-14-adverse-driving-conditions-fog": "audio/unit-14-adverse-driving-conditions-fog.mp3",
  "unit-14-adverse-driving-conditions-night-driving": "audio/unit-14-adverse-driving-conditions-night-driving.mp3",
  "unit-14-adverse-driving-conditions-rain": "audio/unit-14-adverse-driving-conditions-rain.mp3",
  "unit-14-adverse-driving-conditions-stay-out-of-puddles": "audio/unit-14-adverse-driving-conditions-stay-out-of-puddles.mp3",
  "unit-15-preventive-maintenance-preventive-maintenance": "audio/unit-15-preventive-maintenance-preventive-maintenance.mp3",
  "unit-16-conditions-of-carriage-conditions-of-carriage": "audio/unit-16-conditions-of-carriage-conditions-of-carriage.mp3",
  "unit-17-hazardous-materials-hazardous-materials": "audio/unit-17-hazardous-materials-hazardous-materials.mp3",
  "unit-18-emergency-procedures-emergency-procedures": "audio/unit-18-emergency-procedures-emergency-procedures.mp3",
  "unit-19-work-planning-work-planning": "audio/unit-19-work-planning-work-planning.mp3",
  "unit-20-customer-care-customer-care": "audio/unit-20-customer-care-customer-care.mp3",
  "unit-21-the-examination-the-examination": "audio/unit-21-the-examination-the-examination.mp3",
  "unit-22-traffic-signs-traffic-signs": "audio/unit-22-traffic-signs-traffic-signs.mp3",
  "unit-23-model-town-illustrations-model-town-illustrations": "audio/unit-23-model-town-illustrations-model-town-illustrations.mp3",
};

export async function backfillCourseAudio(): Promise<void> {
  try {
    const [{ missing }] = await db
      .select({ missing: sql<number>`count(*)::int` })
      .from(courseLessonsTable)
      .where(sql`audio_url IS NULL`);

    if (missing === 0) {
      logger.info("Course audio backfill — all lessons already have audio_url, skipping");
      return;
    }

    logger.info({ missing }, "Course audio backfill — patching lessons with NULL audio_url…");

    // Build a single UPDATE … FROM (VALUES …) for efficiency
    const entries = Object.entries(AUDIO_URLS);
    const valuesList = entries
      .map(([slug, url]) => `('${slug}', '${url}')`)
      .join(", ");

    await db.execute(sql.raw(`
      UPDATE course_lessons AS cl
      SET    audio_url = v.audio_url
      FROM   (VALUES ${valuesList}) AS v(slug, audio_url)
      WHERE  cl.slug = v.slug
        AND  cl.audio_url IS NULL
    `));

    logger.info({ patched: entries.length }, "Course audio backfill — complete");
  } catch (err) {
    // Non-fatal: log and continue; audio simply won't play until next restart
    logger.error({ err }, "Course audio backfill failed");
  }
}
