/**
 * Seeds the ops database with the Msafiri Founder OS master plan data
 * (24 operating weeks, transaction categories, recurring expenses, settings,
 *  and 137 pre-planned Phase 1 content items).
 *
 * Idempotent — skips if ops_operating_weeks already has rows.
 */
import {
  db,
  opsOperatingWeeksTable,
  opsWeeklyPlansTable,
  opsTransactionCategoriesTable,
  opsRecurringExpensesTable,
  opsSettingsTable,
  opsContentItemsTable,
} from "@workspace/db";
import { sql } from "drizzle-orm";
import type { Logger } from "pino";

// ─── WEEKS (Aug 14 2026 → Jan 16 2027) ──────────────────────────────────────

const WEEKS = [
  { weekNumber: 1,  startDate: "2026-08-14", endDate: "2026-08-20", phase: "1. Stabilize Live App",          plannedCashIn: "10000.00", plannedCashOut: "6987.20" },
  { weekNumber: 2,  startDate: "2026-08-21", endDate: "2026-08-27", phase: "1. Stabilize Live App",          plannedCashIn: "10000.00", plannedCashOut: "4400.00" },
  { weekNumber: 3,  startDate: "2026-08-28", endDate: "2026-09-03", phase: "2. Retention & Paying-User Proof", plannedCashIn: "10000.00", plannedCashOut: "4400.00" },
  { weekNumber: 4,  startDate: "2026-09-04", endDate: "2026-09-10", phase: "2. Retention & Paying-User Proof", plannedCashIn: "10000.00", plannedCashOut: "4400.00" },
  { weekNumber: 5,  startDate: "2026-09-11", endDate: "2026-09-17", phase: "2. Retention & Paying-User Proof", plannedCashIn: "10000.00", plannedCashOut: "6987.20" },
  { weekNumber: 6,  startDate: "2026-09-18", endDate: "2026-09-24", phase: "2. Retention & Paying-User Proof", plannedCashIn: "10000.00", plannedCashOut: "4400.00" },
  { weekNumber: 7,  startDate: "2026-09-25", endDate: "2026-10-01", phase: "3. Corridor Authority",           plannedCashIn: "10000.00", plannedCashOut: "4400.00" },
  { weekNumber: 8,  startDate: "2026-10-02", endDate: "2026-10-08", phase: "3. Corridor Authority",           plannedCashIn: "10000.00", plannedCashOut: "4400.00" },
  { weekNumber: 9,  startDate: "2026-10-09", endDate: "2026-10-15", phase: "3. Corridor Authority",           plannedCashIn: "10000.00", plannedCashOut: "6987.20" },
  { weekNumber: 10, startDate: "2026-10-16", endDate: "2026-10-22", phase: "3. Corridor Authority",           plannedCashIn: "10000.00", plannedCashOut: "4400.00" },
  { weekNumber: 11, startDate: "2026-10-23", endDate: "2026-10-29", phase: "4. Controlled Acquisition",      plannedCashIn: "10000.00", plannedCashOut: "4400.00" },
  { weekNumber: 12, startDate: "2026-10-30", endDate: "2026-11-05", phase: "4. Controlled Acquisition",      plannedCashIn: "10000.00", plannedCashOut: "4400.00" },
  { weekNumber: 13, startDate: "2026-11-06", endDate: "2026-11-12", phase: "4. Controlled Acquisition",      plannedCashIn: "10000.00", plannedCashOut: "6987.20" },
  { weekNumber: 14, startDate: "2026-11-13", endDate: "2026-11-19", phase: "4. Controlled Acquisition",      plannedCashIn: "10000.00", plannedCashOut: "4400.00" },
  { weekNumber: 15, startDate: "2026-11-20", endDate: "2026-11-26", phase: "5. Partnerships & Revenue",      plannedCashIn: "10000.00", plannedCashOut: "4400.00" },
  { weekNumber: 16, startDate: "2026-11-27", endDate: "2026-12-03", phase: "5. Partnerships & Revenue",      plannedCashIn: "10000.00", plannedCashOut: "4400.00" },
  { weekNumber: 17, startDate: "2026-12-04", endDate: "2026-12-10", phase: "5. Partnerships & Revenue",      plannedCashIn: "10000.00", plannedCashOut: "6987.20" },
  { weekNumber: 18, startDate: "2026-12-11", endDate: "2026-12-17", phase: "5. Partnerships & Revenue",      plannedCashIn: "10000.00", plannedCashOut: "4400.00" },
  { weekNumber: 19, startDate: "2026-12-18", endDate: "2026-12-24", phase: "6. Scale What Works",            plannedCashIn: "10000.00", plannedCashOut: "4400.00" },
  { weekNumber: 20, startDate: "2026-12-25", endDate: "2026-12-31", phase: "6. Scale What Works",            plannedCashIn: "10000.00", plannedCashOut: "4400.00" },
  { weekNumber: 21, startDate: "2027-01-01", endDate: "2027-01-07", phase: "6. Scale What Works",            plannedCashIn: "10000.00", plannedCashOut: "6987.20" },
  { weekNumber: 22, startDate: "2027-01-08", endDate: "2027-01-14", phase: "6. Scale What Works",            plannedCashIn: "10000.00", plannedCashOut: "4400.00" },
  { weekNumber: 23, startDate: "2027-01-15", endDate: "2027-01-21", phase: "6. Scale What Works",            plannedCashIn: "10000.00", plannedCashOut: "4400.00" },
  { weekNumber: 24, startDate: "2027-01-22", endDate: "2027-01-28", phase: "6. Scale What Works",            plannedCashIn: "10000.00", plannedCashOut: "4400.00" },
] as const;

// ─── WEEKLY PLANS (objectives + outcomes per week) ───────────────────────────

const WEEKLY_PLANS: { weekNumber: number; mainObjective: string; requiredOutcomes: string[]; cashDecision: string | null }[] = [
  { weekNumber: 1,  mainObjective: "Ship nothing new; fix everything that can block a paying user", requiredOutcomes: ["Fix every crash or error blocking a user from paying.", "Confirm subscription flow works end to end on both stores.", "Set up error/crash monitoring.", "Respond to all support in under 24 hours.", "One corridor; one content block; four posts.", "Make the first partner call.", "Set up the fuel/cost tracker."], cashDecision: "Protect Replit, field ops, product and content. Reserve any surplus." },
  { weekNumber: 2,  mainObjective: "Understand exactly why the first users downloaded, stayed or left", requiredOutcomes: ["Contact every tester or early downloader.", "Document three verbatim user problems.", "Fix the top support issue from Week 1.", "Repeat/refresh the same corridor.", "Turn one user insight into a content post.", "Ask one potential partner for feedback.", "Log actual spend vs plan."], cashDecision: "No new spend categories. Reserve transfer if surplus." },
  { weekNumber: 3,  mainObjective: "Reduce support friction", requiredOutcomes: ["Create support FAQ and response templates.", "Contact users who downloaded but did not pay.", "Repeat/refresh the same corridor; do not expand yet.", "Turn support questions into 2 educational posts.", "Test store-page CTA versus direct feature CTA.", "Make first two partner calls.", "Review actual fuel cost per km and trip output."], cashDecision: "No new spend. Reserve transfer if surplus." },
  { weekNumber: 4,  mainObjective: "Measure retention honestly", requiredOutcomes: ["Instrument or validate D1/D7 key-action reporting.", "Review first retention cohort and cancellation reasons.", "Add missing speed-limit/sign evidence.", "Create a user problem → feature → outcome story.", "One free community post in a relevant group.", "Offer one no-cost feedback/demo session.", "Ads gate review; default remains no."], cashDecision: "Reserve KES 1,000 for possible ads gate test in week 5." },
  { weekNumber: 5,  mainObjective: "Create the paying-user proof pack", requiredOutcomes: ["Fix the top retained-user request only.", "Secure 2 consented testimonials or anonymized quotes.", "Capture clean evidence and app demo B-roll.", "Publish proof, not promises; 4 core posts.", "Test testimonial vs founder explanation.", "Send proof pack to 3 partners.", "Review runway and recurring costs."], cashDecision: "Replit billing week. Reserve if possible." },
  { weekNumber: 6,  mainObjective: "Make the app indispensable on one route", requiredOutcomes: ["Add verified speed-limit data for the chosen corridor.", "Reach 10 verified road records on that corridor.", "Record a clean field demo on the priority corridor.", "4 posts anchored to the same corridor.", "Ask 3 corridor users for accuracy feedback.", "Approach 2 corridor-relevant businesses.", "No spend without linked trip/output."], cashDecision: "No new categories. Reserve KES 1,500." },
  { weekNumber: 7,  mainObjective: "Own one corridor", requiredOutcomes: ["Improve route/corridor accuracy and freshness workflow.", "Ask users on that corridor for accuracy feedback.", "Deep-verify one named corridor.", "Launch a corridor-specific weekly series.", "Route-specific WhatsApp/community sharing.", "Approach 2 corridor-relevant businesses.", "Fuel spend per verified record is known."], cashDecision: "Reserve KES 1,500 if surplus." },
  { weekNumber: 8,  mainObjective: "Build the verification loop", requiredOutcomes: ["Add/report verification status clearly in product/ops.", "Invite trusted users to submit evidence.", "Create repeatable field verification SOP.", "Show how verification works behind the scenes.", "Test a contributor recognition loop.", "Ask a road-safety group for process feedback.", "No spend without linked trip/output."], cashDecision: "Reserve KES 1,500." },
  { weekNumber: 9,  mainObjective: "Improve conversion before reach", requiredOutcomes: ["Clarify paywall value, price and cancellation language.", "Review 10 paywall sessions or user explanations.", "Capture one field scenario tied to paid value.", "Test problem-first versus feature-first CTA.", "No scale; one controlled creative test only.", "Discuss subscription offer with one partner.", "Compare gross sales, fees and cash received."], cashDecision: "Replit billing week. Reserve if possible." },
  { weekNumber: 10, mainObjective: "Create a referral mechanism", requiredOutcomes: ["Build or document simple referral tracking.", "Ask paying users what reward would matter.", "Use the same priority corridor.", "Publish 'who should use Msafiri?' and referral CTA.", "Run a manual referral test.", "Give partners unique link/code proposal.", "Set a zero-fraud referral rule."], cashDecision: "Reserve KES 1,500." },
  { weekNumber: 11, mainObjective: "Test the first paid acquisition unit", requiredOutcomes: ["Do not change product and ad variables simultaneously.", "Confirm new users receive support.", "No new corridor expansion this week.", "Use proven organic creative only.", "Run one capped Meta test if all gates pass.", "No creator payment in same week.", "Maximum KES 1,000 and same-day logging."], cashDecision: "KES 1,000 ads cap if gates pass. Reserve if not." },
  { weekNumber: 12, mainObjective: "Validate paid unit economics", requiredOutcomes: ["Measure CPI, activation, paid conversion, CAC.", "Kill or iterate based on evidence, not hope.", "Keep the same corridor.", "Publish the result — what worked, what did not.", "Only if gate passes: second creator test.", "Introduce a partner to one paying user.", "Update cash model with actual paid acquisition cost."], cashDecision: "Reserve KES 1,500." },
  { weekNumber: 13, mainObjective: "Prepare the partnership value proposition", requiredOutcomes: ["Document fleet/insurance/driving-school user scenarios.", "Identify three specific local partners by name.", "Create a one-page partnership brief.", "Publish one case study or proof post.", "Test paid creative with a corridor partner mention.", "Present the brief to one partner.", "Cost-per-verified-record is documented."], cashDecision: "Replit billing week. Reserve if possible." },
  { weekNumber: 14, mainObjective: "Have the first partnership conversation", requiredOutcomes: ["First formal meeting or call with a named partner.", "Understand their decision criteria.", "Show the paying-user proof pack.", "Publish 4 posts; no new content experiment.", "No paid acquisition this week.", "Document partnership learning.", "Log all trip and content costs."], cashDecision: "Reserve KES 1,500." },
  { weekNumber: 15, mainObjective: "Convert a pilot partnership", requiredOutcomes: ["Agree on a pilot format, scope and success metric.", "Assign a partner contact point.", "Expand verified records to the partner corridor.", "Content supports the partner story.", "No new paid acquisition until partnership economics are clear.", "Document the pilot terms.", "Separate partnership cost from ops cost."], cashDecision: "Reserve KES 1,500." },
  { weekNumber: 16, mainObjective: "Deliver the pilot result", requiredOutcomes: ["Complete the agreed pilot output.", "Collect partner feedback.", "Measure any user, revenue or data benefit.", "Publish 4 posts anchored to partnership evidence.", "Decide: repeat, expand, or close the pilot.", "Document result for next partner conversation.", "Update cash plan based on any partnership revenue."], cashDecision: "Reserve KES 1,500." },
  { weekNumber: 17, mainObjective: "Scale what is working; stop what is not", requiredOutcomes: ["Identify the one acquisition channel with best unit economics.", "Double the budget or effort on that channel only.", "Cut or pause the weakest channel.", "Content output stays at 4 core posts.", "Test one new angle on the proven channel.", "No new partnerships; consolidate existing.", "Update and publish the ops model."], cashDecision: "Replit billing week. Reserve if possible." },
  { weekNumber: 18, mainObjective: "Harden the business before Jan 2027", requiredOutcomes: ["Review all recurring costs; cut non-essential spend.", "Confirm the subscription price is still the right one.", "Fix any compliance, safety or support backlog.", "4 content posts; repurpose the best Week 1–17 assets.", "One partner check-in.", "Document what made users pay and what made them cancel.", "Set the Week 19–24 operating plan."], cashDecision: "Reserve KES 1,500." },
  { weekNumber: 19, mainObjective: "Operate the proven playbook", requiredOutcomes: ["Run the field trip.", "Publish 4 posts.", "Answer all support.", "Log all spend.", "One acquisition experiment.", "One partner conversation.", "Weekly review done by Sunday."], cashDecision: "Reserve KES 1,500." },
  { weekNumber: 20, mainObjective: "Christmas and New Year content surge", requiredOutcomes: ["Plan holiday safety and travel content.", "Pre-schedule posts for Christmas week.", "Support response templates for holiday queries.", "One partner co-post or mention if agreed.", "No new paid experiment during holiday.", "Log all spend.", "Weekly review done by Sunday."], cashDecision: "Reserve KES 1,500." },
  { weekNumber: 21, mainObjective: "New Year acquisition push", requiredOutcomes: ["New Year driving resolution content.", "One controlled paid acquisition test.", "Support for new users onboarding.", "Creator test if unit economics allow.", "Log all spend.", "Partner check-in.", "Weekly review done by Sunday."], cashDecision: "Replit billing week. Reserve if possible." },
  { weekNumber: 22, mainObjective: "Consolidate Q1 2027 plan", requiredOutcomes: ["Document all learnings from Weeks 1–21.", "Set Q1 2027 objectives.", "Review and update the subscription price.", "4 core posts.", "Partner pipeline review.", "Log all spend.", "Weekly review done by Sunday."], cashDecision: "Reserve KES 1,500." },
  { weekNumber: 23, mainObjective: "Operate the playbook", requiredOutcomes: ["Run the field trip.", "Publish 4 posts.", "Answer all support.", "Log all spend.", "One acquisition experiment.", "One partner conversation.", "Weekly review done by Sunday."], cashDecision: "Reserve KES 1,500." },
  { weekNumber: 24, mainObjective: "24-week retrospective and next plan", requiredOutcomes: ["Document all 24-week learnings.", "Publish a founder retrospective post.", "Set the next 24-week plan.", "Partner pipeline: what to close, what to expand.", "Review subscription price.", "Review recurring costs.", "Set Week 25 objectives."], cashDecision: "Reserve KES 1,500." },
];

// ─── TRANSACTION CATEGORIES ──────────────────────────────────────────────────

const CATEGORIES = [
  { name: "Founder Funding",        type: "income",  description: "Weekly founder cash contribution", isSystem: true },
  { name: "Subscription Revenue",   type: "income",  description: "App Store / Play Store subscription cash received", isSystem: true },
  { name: "Replit Hosting",         type: "expense", description: "Monthly Replit subscription (USD billed)", isSystem: true },
  { name: "Fuel & Field Ops",       type: "expense", description: "Fuel, parking, tolls and field trip costs", isSystem: true },
  { name: "Product / Data",         type: "expense", description: "Testing, analytics tools, small repairs", isSystem: true },
  { name: "Content Production",     type: "expense", description: "Props, captions, phone accessories, production costs", isSystem: true },
  { name: "Admin / Support",        type: "expense", description: "Communication, printing, small admin costs", isSystem: true },
  { name: "Ads",                    type: "expense", description: "Controlled paid advertising spend (gate-controlled)", isSystem: true },
  { name: "Micro-Creator",          type: "expense", description: "Creator partnership payments (gate-controlled)", isSystem: true },
  { name: "Contractor",             type: "expense", description: "Output-based contractor payments", isSystem: true },
  { name: "One-time / Compliance",  type: "expense", description: "Business registration, compliance, one-time tools", isSystem: true },
  { name: "Reserve Transfer",       type: "reserve", description: "Weekly transfer to business reserve", isSystem: true },
  { name: "Store / Processor Fees", type: "expense", description: "App Store / Play Store processing fees (deducted from gross)", isSystem: true },
  { name: "Refund",                 type: "expense", description: "Subscription refunds issued", isSystem: true },
  { name: "Other Income",           type: "income",  description: "Miscellaneous income", isSystem: false },
  { name: "Other Expense",          type: "expense", description: "Miscellaneous expense", isSystem: false },
] as const;

// ─── RECURRING EXPENSES ──────────────────────────────────────────────────────
// Resolved after categories are inserted; indices refer to CATEGORIES array

const RECURRING_EXPENSES = [
  { name: "Replit Hosting",           amountUsd: "20.00", currencyType: "USD", amountKes: "2587.20", frequency: "monthly",  categoryName: "Replit Hosting",   nextBillingDate: "2026-08-14", notes: "USD 20/month at 129.36 KES/USD planning rate. Protect before any optional spend." },
  { name: "Founder Contribution",     amountUsd: null,    currencyType: "KES", amountKes: "10000.00", frequency: "weekly",  categoryName: "Founder Funding",  nextBillingDate: "2026-08-14", notes: "KES 10,000 every Friday. First payment: 14 Aug 2026." },
  { name: "Field Operations Budget",  amountUsd: null,    currencyType: "KES", amountKes: "2500.00",  frequency: "weekly",  categoryName: "Fuel & Field Ops", nextBillingDate: "2026-08-17", notes: "Fuel (KES 2,140 at KES 214/L, 12km/L, 120km/week) + KES 360 parking/tolls." },
  { name: "Product / Data Budget",    amountUsd: null,    currencyType: "KES", amountKes: "750.00",   frequency: "weekly",  categoryName: "Product / Data",   nextBillingDate: "2026-08-17", notes: "Small repairs, data, testing and necessary app operations." },
  { name: "Content Production Budget",amountUsd: null,    currencyType: "KES", amountKes: "750.00",   frequency: "weekly",  categoryName: "Content Production",nextBillingDate: "2026-08-17", notes: "Low-cost props, captions/data, or essential production; phone-first by default." },
  { name: "Admin / Support Budget",   amountUsd: null,    currencyType: "KES", amountKes: "400.00",   frequency: "weekly",  categoryName: "Admin / Support",  nextBillingDate: "2026-08-17", notes: "Support communication, printing, small admin and transaction costs." },
] as const;

// ─── CONTENT ITEMS (Phase 1 Calendar — 137 posts across 20 weeks) ─────────────

const CONTENT: {
  weekNumber: number; scheduledDate: string; title: string; pillar: string | null;
  format: string | null; platforms: string[]; angle: string | null; hook: string | null;
  captionSeed: string | null; cta: string | null; status: string; isCore: boolean;
  founderMinutes: number | null; notes: string | null;
}[] = [
  // ── Week 1: Launch the road-intelligence promise ──────────────────────────
  { weekNumber: 1, scheduledDate: "2026-08-17", title: "Msafiri Road Check: Speed camera alerts", pillar: "Road Intelligence", format: "Hero / Reel", platforms: ["TikTok","Instagram Reels","YouTube Shorts","Facebook Reels","YouTube"], angle: "Anchor episode that turns this week's theme into a road story people can recognize.", hook: "We tested Mombasa Road / city commute: what should a daily nairobi commuter know before driving it this week?", captionSeed: "Road intelligence should feel practical, not complicated. Here is what stood out on Mombasa Road / city commute.", cta: "Tell us which road we should check next.", status: "draft", isCore: true, founderMinutes: 75, notes: "POV drive, 3 timestamped moments, map/context overlay, quick Msafiri screen, clear payoff." },
  { weekNumber: 1, scheduledDate: "2026-08-18", title: "Feature in the Wild: Speed camera alerts", pillar: "Product / Feature Proof", format: "Short-form video", platforms: ["Instagram Reels","TikTok","YouTube Shorts","Facebook Reels"], angle: "Show the feature solving one real driving moment without turning the video into an ad.", hook: "Speed camera alerts only makes sense when you are rushing and forget the road still has limits; here is the 30-second version.", captionSeed: "A feature is only useful if it helps in the exact moment a driver needs it.", cta: "Try Msafiri on your next drive.", status: "draft", isCore: true, founderMinutes: 45, notes: "Phone mount, screen-record, before/after comparison, one clean feature payoff." },
  { weekNumber: 1, scheduledDate: "2026-08-19", title: "Kenyan Driver Problems: Speed camera alerts", pillar: "Kenyan Driving Reality", format: "Skit", platforms: ["TikTok","Instagram Reels","Facebook Reels","YouTube Shorts"], angle: "Relatable driver tension; make people laugh, then attach a practical Msafiri angle.", hook: "POV: you are rushing and forget the road still has limits and everyone in the car suddenly becomes a driving expert.", captionSeed: "Every driver knows this argument. The smart move is having better information before the argument starts.", cta: "Tag the driver who does this.", status: "idea", isCore: false, founderMinutes: 25, notes: "Driver/passenger skit, quick reaction cuts, exaggerated but familiar Kenyan driving moment." },
  { weekNumber: 1, scheduledDate: "2026-08-20", title: "Founder Files: Speed camera alerts", pillar: "Founder / BTS", format: "Founder-to-camera", platforms: ["Instagram Reels","TikTok","YouTube Shorts","LinkedIn"], angle: "Peter explains the product decision, tradeoff, or local insight behind the week's feature.", hook: "Peter here — this is why we built speed camera alerts for Kenyan drivers, not just generic drivers.", captionSeed: "The goal is not another app on your phone. The goal is a calmer, more prepared drive.", cta: "Follow Msafiri as we build for Kenyan roads.", status: "draft", isCore: true, founderMinutes: 45, notes: "Peter in car or office, quick cutaways to road test, product screen and handwritten notes." },
  { weekNumber: 1, scheduledDate: "2026-08-21", title: "Road Mythbusters: Speed camera alerts", pillar: "Debate / Mythbusters", format: "Short-form video", platforms: ["TikTok","Instagram Reels","YouTube Shorts","Facebook Reels"], angle: "Open a controlled debate while ending with responsible road-safety framing.", hook: "Hot take: if you're slowing down only for cameras you haven't understood speed limits yet.", captionSeed: "Debate is useful only if it makes us better drivers. What is your honest view?", cta: "Agree or disagree? Give your reason.", status: "idea", isCore: false, founderMinutes: 25, notes: "Split screen: claim vs reality, quick poll sticker, Peter closing with safe takeaway." },
  { weekNumber: 1, scheduledDate: "2026-08-22", title: "Road Safety KE: Speed camera alerts", pillar: "Education / Safety", format: "Explainer", platforms: ["Instagram Reels","TikTok","YouTube Shorts","Facebook Reels"], angle: "A calm, credible explainer that earns trust before asking for an install.", hook: "Here is what a Kenyan traffic camera actually measures — and what it does not.", captionSeed: "Knowing how the road works is the first step to driving it better.", cta: "Share this with someone who needs to know.", status: "idea", isCore: false, founderMinutes: 30, notes: "On-screen text overlay, Msafiri map view, clear and calm narration." },
  { weekNumber: 1, scheduledDate: "2026-08-23", title: "Before You Drive: Speed camera alerts", pillar: "Education / Safety", format: "Checklist Reel", platforms: ["Instagram Reels","TikTok","YouTube Shorts","Facebook Reels","Instagram Stories"], angle: "A saveable checklist people can use before a real drive.", hook: "Save this launch the road-intelligence promise checklist before your next drive.", captionSeed: "A good drive often starts before the engine starts. Keep this simple checklist close.", cta: "Save this before your next drive.", status: "idea", isCore: false, founderMinutes: 20, notes: "Checklist overlay, hands-on car/phone shots, one item per beat, final saved-card frame." },
  // ── Week 2: Proof when stories disagree ──────────────────────────────────
  { weekNumber: 2, scheduledDate: "2026-08-24", title: "Msafiri Road Check: Built-in Dashcam", pillar: "Road Intelligence", format: "Hero / Reel", platforms: ["TikTok","Instagram Reels","YouTube Shorts","Facebook Reels","YouTube"], angle: "Anchor episode that turns this week's theme into a road story people can recognize.", hook: "We drove Waiyaki Way / Westlands run this week — here is what the dashcam caught that mattered.", captionSeed: "Road intelligence should feel practical, not complicated. Here is what stood out on Waiyaki Way / Westlands run.", cta: "Tell us which road we should check next.", status: "draft", isCore: true, founderMinutes: 75, notes: "POV drive with dashcam active, 3 key moments, overlay Msafiri screen." },
  { weekNumber: 2, scheduledDate: "2026-08-25", title: "Feature in the Wild: Built-in Dashcam", pillar: "Product / Feature Proof", format: "Short-form video", platforms: ["Instagram Reels","TikTok","YouTube Shorts","Facebook Reels"], angle: "Show the feature solving one real driving moment without turning the video into an ad.", hook: "Built-in Dashcam only makes sense when a story needs to be settled; here is the 30-second version.", captionSeed: "A feature is only useful if it helps in the exact moment a driver needs it.", cta: "Try Msafiri on your next drive.", status: "draft", isCore: true, founderMinutes: 45, notes: "Phone mount, screen-record, before/after comparison, one clean feature payoff." },
  { weekNumber: 2, scheduledDate: "2026-08-26", title: "Kenyan Driver Problems: Built-in Dashcam", pillar: "Kenyan Driving Reality", format: "Skit", platforms: ["TikTok","Instagram Reels","Facebook Reels","YouTube Shorts"], angle: "Relatable driver tension; make people laugh, then attach a practical Msafiri angle.", hook: "POV: someone bumps your car and suddenly nobody saw anything.", captionSeed: "Every driver knows this argument. The smart move is having better information before the argument starts.", cta: "Tag the driver who does this.", status: "idea", isCore: false, founderMinutes: 25, notes: "Driver/passenger skit around incident evidence dispute." },
  { weekNumber: 2, scheduledDate: "2026-08-27", title: "Founder Files: Built-in Dashcam", pillar: "Founder / BTS", format: "Founder-to-camera", platforms: ["Instagram Reels","TikTok","YouTube Shorts","LinkedIn"], angle: "Peter explains the product decision, tradeoff, or local insight behind the week's feature.", hook: "Peter here — this is why we built a dashcam into a road-safety app, not a standalone recorder.", captionSeed: "The goal is not another app on your phone. The goal is a calmer, more prepared drive.", cta: "Follow Msafiri as we build for Kenyan roads.", status: "draft", isCore: true, founderMinutes: 45, notes: "Peter in car, dashcam running, explains the decision." },
  { weekNumber: 2, scheduledDate: "2026-08-28", title: "Road Mythbusters: Built-in Dashcam", pillar: "Debate / Mythbusters", format: "Short-form video", platforms: ["TikTok","Instagram Reels","YouTube Shorts","Facebook Reels"], angle: "Open a controlled debate while ending with responsible road-safety framing.", hook: "Hot take: every daily driver should have video evidence, even for short trips.", captionSeed: "Debate is useful only if it makes us better drivers. What is your honest view?", cta: "Agree or disagree? Give your reason.", status: "idea", isCore: false, founderMinutes: 25, notes: "Split screen: claim vs reality, quick poll sticker, Peter closing with safe takeaway." },
  { weekNumber: 2, scheduledDate: "2026-08-29", title: "Road Safety KE: Built-in Dashcam", pillar: "Education / Safety", format: "Explainer", platforms: ["Instagram Reels","TikTok","YouTube Shorts"], angle: "A calm, credible explainer about dashcam evidence in Kenya.", hook: "Can phone dashcam footage actually be used as evidence in Kenya? Here is what we found.", captionSeed: "Knowing how the road works is the first step to driving it better.", cta: "Share this with someone who drives daily.", status: "idea", isCore: false, founderMinutes: 30, notes: "On-screen text overlay, legal context, responsible framing." },
  { weekNumber: 2, scheduledDate: "2026-08-30", title: "Before You Drive: Built-in Dashcam", pillar: "Education / Safety", format: "Checklist Reel", platforms: ["Instagram Reels","TikTok","YouTube Shorts","Facebook Reels"], angle: "A saveable checklist for evidence-ready driving.", hook: "Save this proof when stories disagree checklist before your next drive.", captionSeed: "A good drive often starts before the engine starts.", cta: "Save this before your next drive.", status: "idea", isCore: false, founderMinutes: 20, notes: "Checklist overlay, one item per beat." },
  // ── Week 3: First 10 minutes after an accident ────────────────────────────
  { weekNumber: 3, scheduledDate: "2026-08-31", title: "Msafiri Road Check: Accident Assistant", pillar: "Road Intelligence", format: "Hero / Reel", platforms: ["TikTok","Instagram Reels","YouTube Shorts","Facebook Reels","YouTube"], angle: "Anchor episode around accident-readiness on Thika Road.", hook: "We drove Thika Road / busy junctions this week — here is what every driver should know before an incident.", captionSeed: "Road intelligence should feel practical, not complicated.", cta: "Tell us which road we should check next.", status: "draft", isCore: true, founderMinutes: 75, notes: "POV drive on Thika Road, 3 key moments, Accident Assistant demo overlay." },
  { weekNumber: 3, scheduledDate: "2026-09-01", title: "Feature in the Wild: Accident Assistant", pillar: "Product / Feature Proof", format: "Short-form video", platforms: ["Instagram Reels","TikTok","YouTube Shorts","Facebook Reels"], angle: "Show Accident Assistant solving one real driving moment.", hook: "Accident Assistant only makes sense when everyone is shaken and nobody knows what to collect first; here is the 30-second version.", captionSeed: "A feature is only useful if it helps in the exact moment a driver needs it.", cta: "Try Msafiri on your next drive.", status: "draft", isCore: true, founderMinutes: 45, notes: "Phone mount, screen-record, before/after comparison, one clean feature payoff." },
  { weekNumber: 3, scheduledDate: "2026-09-02", title: "Kenyan Driver Problems: Accident Assistant", pillar: "Kenyan Driving Reality", format: "Skit", platforms: ["TikTok","Instagram Reels","Facebook Reels","YouTube Shorts"], angle: "Relatable skit about post-accident confusion.", hook: "POV: everyone is shaken and nobody knows what to collect first and everyone in the car suddenly becomes a driving expert.", captionSeed: "Every driver knows this argument. The smart move is having better information before the argument starts.", cta: "Tag the driver who does this.", status: "idea", isCore: false, founderMinutes: 25, notes: "Driver/passenger skit, quick reaction cuts." },
  { weekNumber: 3, scheduledDate: "2026-09-03", title: "Founder Files: Accident Assistant", pillar: "Founder / BTS", format: "Founder-to-camera", platforms: ["Instagram Reels","TikTok","YouTube Shorts","LinkedIn"], angle: "Peter explains why Accident Assistant was built for Kenyan drivers.", hook: "Peter here — this is why we built Accident Assistant for Kenyan drivers, not just generic drivers.", captionSeed: "The goal is not another app on your phone. The goal is a calmer, more prepared drive.", cta: "Follow Msafiri as we build for Kenyan roads.", status: "draft", isCore: true, founderMinutes: 45, notes: "Peter in car or office, quick cutaways to road test." },
  { weekNumber: 3, scheduledDate: "2026-09-04", title: "Road Mythbusters: Accident Assistant", pillar: "Debate / Mythbusters", format: "Short-form video", platforms: ["TikTok","Instagram Reels","YouTube Shorts","Facebook Reels"], angle: "Controlled debate about post-accident preparedness.", hook: "Hot take: most drivers think they know what to do after a crash until it happens.", captionSeed: "Debate is useful only if it makes us better drivers.", cta: "Agree or disagree? Give your reason.", status: "idea", isCore: false, founderMinutes: 25, notes: "Split screen: claim vs reality, quick poll sticker." },
  { weekNumber: 3, scheduledDate: "2026-09-05", title: "Road Safety KE: Accident Assistant", pillar: "Education / Safety", format: "Explainer", platforms: ["Instagram Reels","TikTok","YouTube Shorts"], angle: "Calm explainer on what to do in the first 10 minutes after a crash.", hook: "Here is what Kenyan law says you should do in the first 10 minutes after a road incident.", captionSeed: "Knowing how the road works is the first step to driving it better.", cta: "Share this with someone who drives daily.", status: "idea", isCore: false, founderMinutes: 30, notes: "On-screen text overlay, legal references, responsible framing." },
  { weekNumber: 3, scheduledDate: "2026-09-06", title: "Before You Drive: Accident Assistant", pillar: "Education / Safety", format: "Checklist Reel", platforms: ["Instagram Reels","TikTok","YouTube Shorts","Facebook Reels"], angle: "A saveable post-incident checklist.", hook: "Save this first 10 minutes after an accident checklist before your next drive.", captionSeed: "A good drive often starts before the engine starts.", cta: "Save this before your next drive.", status: "idea", isCore: false, founderMinutes: 20, notes: "Checklist overlay, one item per beat." },
  // ── Weeks 4–20 follow the same 4-core + 3-optional pattern ──────────────
  // Week 4: Nairobi commute survival — Road alerts
  { weekNumber: 4, scheduledDate: "2026-09-07", title: "Msafiri Road Check: Road alerts", pillar: "Road Intelligence", format: "Hero / Reel", platforms: ["TikTok","Instagram Reels","YouTube Shorts","Facebook Reels","YouTube"], angle: "Compare a normal commute with and without advance road context.", hook: "We drove Ngong Road / Langata Road this week — here is what every Nairobi commuter should know.", captionSeed: "Road intelligence should feel practical, not complicated.", cta: "Tell us which road we should check next.", status: "draft", isCore: true, founderMinutes: 75, notes: "POV drive, 3 timestamped moments, map overlay, Msafiri road alerts demo." },
  { weekNumber: 4, scheduledDate: "2026-09-08", title: "Feature in the Wild: Road alerts", pillar: "Product / Feature Proof", format: "Short-form video", platforms: ["Instagram Reels","TikTok","YouTube Shorts","Facebook Reels"], angle: "Show road alerts solving one real commute moment.", hook: "Road alerts only makes sense when you are rushing and do not know what is ahead; here is the 30-second version.", captionSeed: "A feature is only useful if it helps in the exact moment a driver needs it.", cta: "Try Msafiri on your next drive.", status: "draft", isCore: true, founderMinutes: 45, notes: "Phone mount, screen-record, before/after, one clean payoff." },
  { weekNumber: 4, scheduledDate: "2026-09-09", title: "Kenyan Driver Problems: Road alerts", pillar: "Kenyan Driving Reality", format: "Skit", platforms: ["TikTok","Instagram Reels","Facebook Reels","YouTube Shorts"], angle: "Relatable commuter tension — the road surprises that could have been avoided.", hook: "POV: you left home on time and Ngong Road had other plans.", captionSeed: "Every driver knows this argument. The smart move is having better information before the argument starts.", cta: "Tag the driver who does this.", status: "idea", isCore: false, founderMinutes: 25, notes: "Driver skit, quick reaction cuts, Nairobi traffic context." },
  { weekNumber: 4, scheduledDate: "2026-09-10", title: "Founder Files: Road alerts", pillar: "Founder / BTS", format: "Founder-to-camera", platforms: ["Instagram Reels","TikTok","YouTube Shorts","LinkedIn"], angle: "Peter explains the decision behind Msafiri road alerts.", hook: "Peter here — this is why road alerts in Msafiri work differently from a generic Google Maps notification.", captionSeed: "The goal is not another app on your phone. The goal is a calmer, more prepared drive.", cta: "Follow Msafiri as we build for Kenyan roads.", status: "draft", isCore: true, founderMinutes: 45, notes: "Peter in car or office." },
  { weekNumber: 4, scheduledDate: "2026-09-11", title: "Road Mythbusters: Road alerts", pillar: "Debate / Mythbusters", format: "Short-form video", platforms: ["TikTok","Instagram Reels","YouTube Shorts","Facebook Reels"], angle: "Debate: are road apps making drivers lazy or smarter?", hook: "Hot take: using a road-alert app does not make you a better driver. Or does it?", captionSeed: "Debate is useful only if it makes us better drivers.", cta: "Agree or disagree? Give your reason.", status: "idea", isCore: false, founderMinutes: 25, notes: "Split screen, poll sticker." },
  { weekNumber: 4, scheduledDate: "2026-09-12", title: "Road Safety KE: Road alerts", pillar: "Education / Safety", format: "Explainer", platforms: ["Instagram Reels","TikTok","YouTube Shorts"], angle: "Explainer on how community-sourced road alerts work.", hook: "Here is how Msafiri road alerts are verified — and what makes them different from rumours.", captionSeed: "Knowing how the road works is the first step to driving it better.", cta: "Share this with someone who drives the same corridor.", status: "idea", isCore: false, founderMinutes: 30, notes: "On-screen text overlay, verification flow." },
  { weekNumber: 4, scheduledDate: "2026-09-13", title: "Before You Drive: Road alerts", pillar: "Education / Safety", format: "Checklist Reel", platforms: ["Instagram Reels","TikTok","YouTube Shorts","Facebook Reels"], angle: "A saveable Nairobi commute checklist.", hook: "Save this Nairobi commute survival checklist before your next drive.", captionSeed: "A good drive often starts before the engine starts.", cta: "Save this before your next drive.", status: "idea", isCore: false, founderMinutes: 20, notes: "Checklist overlay." },
  // Week 5: Owning the cost of car care
  { weekNumber: 5, scheduledDate: "2026-09-14", title: "Msafiri Road Check: Vehicle care demo", pillar: "Road Intelligence", format: "Hero / Reel", platforms: ["TikTok","Instagram Reels","YouTube Shorts","Facebook Reels","YouTube"], angle: "Car care on Kenyan roads from a driver-cost angle.", hook: "We drove Eastern Bypass / garage errands this week — here is the real cost every Kenyan driver should know.", captionSeed: "Road intelligence should feel practical, not complicated.", cta: "Tell us which road we should check next.", status: "idea", isCore: true, founderMinutes: 75, notes: "POV drive, garage visit, cost breakdown, Msafiri vehicle care demo." },
  { weekNumber: 5, scheduledDate: "2026-09-15", title: "Feature in the Wild: Vehicle care demo", pillar: "Product / Feature Proof", format: "Short-form video", platforms: ["Instagram Reels","TikTok","YouTube Shorts","Facebook Reels"], angle: "Show vehicle care feature solving a real driver cost moment.", hook: "Vehicle care tracking only makes sense when you keep paying for the same repairs; here is the 30-second version.", captionSeed: "A feature is only useful if it helps in the exact moment a driver needs it.", cta: "Try Msafiri on your next drive.", status: "idea", isCore: true, founderMinutes: 45, notes: "Screen-record, vehicle log, cost comparison." },
  { weekNumber: 5, scheduledDate: "2026-09-16", title: "Kenyan Driver Problems: Vehicle care demo", pillar: "Kenyan Driving Reality", format: "Skit", platforms: ["TikTok","Instagram Reels","Facebook Reels","YouTube Shorts"], angle: "The relatable pain of mechanic visits that feel like a mystery.", hook: "POV: you go to the mechanic for one thing and somehow you need four more things replaced.", captionSeed: "Every driver knows this argument.", cta: "Tag the driver who does this.", status: "idea", isCore: false, founderMinutes: 25, notes: "Mechanic skit, relatable Kenya driving moment." },
  { weekNumber: 5, scheduledDate: "2026-09-17", title: "Founder Files: Vehicle care demo", pillar: "Founder / BTS", format: "Founder-to-camera", platforms: ["Instagram Reels","TikTok","YouTube Shorts","LinkedIn"], angle: "Peter explains vehicle maintenance tracking in Msafiri.", hook: "Peter here — this is why we built vehicle care tracking into a road-safety app.", captionSeed: "The goal is not another app on your phone. The goal is a calmer, more prepared drive.", cta: "Follow Msafiri as we build for Kenyan roads.", status: "idea", isCore: true, founderMinutes: 45, notes: "Peter in car or office, product screen." },
  { weekNumber: 5, scheduledDate: "2026-09-18", title: "Road Mythbusters: Vehicle care demo", pillar: "Debate / Mythbusters", format: "Short-form video", platforms: ["TikTok","Instagram Reels","YouTube Shorts","Facebook Reels"], angle: "Debate: is tracking your car costs a driver habit or an obsession?", hook: "Hot take: most Kenyan drivers do not know their actual cost per kilometre.", captionSeed: "Debate is useful only if it makes us better drivers.", cta: "Agree or disagree?", status: "idea", isCore: false, founderMinutes: 25, notes: "Split screen, poll sticker." },
  { weekNumber: 5, scheduledDate: "2026-09-19", title: "Road Safety KE: Vehicle care demo", pillar: "Education / Safety", format: "Explainer", platforms: ["Instagram Reels","TikTok","YouTube Shorts"], angle: "Explainer on how poor vehicle maintenance increases road risk.", hook: "Here is how an unmaintained vehicle creates a road hazard — and what you can do about it.", captionSeed: "Knowing how the road works is the first step to driving it better.", cta: "Share this with someone who drives daily.", status: "idea", isCore: false, founderMinutes: 30, notes: "On-screen text, safety data, responsible framing." },
  { weekNumber: 5, scheduledDate: "2026-09-20", title: "Before You Drive: Vehicle care demo", pillar: "Education / Safety", format: "Checklist Reel", platforms: ["Instagram Reels","TikTok","YouTube Shorts","Facebook Reels"], angle: "A saveable vehicle care checklist.", hook: "Save this owning the cost of car care checklist before your next service.", captionSeed: "A good drive often starts before the engine starts.", cta: "Save this.", status: "idea", isCore: false, founderMinutes: 20, notes: "Checklist overlay." },
  // Week 6: Weekend drives and nearby decisions
  { weekNumber: 6, scheduledDate: "2026-09-21", title: "Msafiri Road Check: Find Nearby demo", pillar: "Road Intelligence", format: "Hero / Reel", platforms: ["TikTok","Instagram Reels","YouTube Shorts","Facebook Reels","YouTube"], angle: "Planning a Nairobi to Naivasha trip with Msafiri.", hook: "We planned a Nairobi to Naivasha drive this weekend — here is what Msafiri surfaced that mattered.", captionSeed: "Road intelligence should feel practical, not complicated.", cta: "Tell us which road we should check next.", status: "idea", isCore: true, founderMinutes: 75, notes: "Road check on highway, Find Nearby demo, Msafiri screen overlay." },
  { weekNumber: 6, scheduledDate: "2026-09-22", title: "Feature in the Wild: Find Nearby demo", pillar: "Product / Feature Proof", format: "Short-form video", platforms: ["Instagram Reels","TikTok","YouTube Shorts","Facebook Reels"], angle: "Show Find Nearby solving a real weekend drive decision.", hook: "Find Nearby only makes sense when you are on the road and need a reliable decision fast; here is the 30-second version.", captionSeed: "A feature is only useful if it helps in the exact moment a driver needs it.", cta: "Try Msafiri on your next drive.", status: "idea", isCore: true, founderMinutes: 45, notes: "Screen-record, before/after, one clean payoff." },
  { weekNumber: 6, scheduledDate: "2026-09-23", title: "Kenyan Driver Problems: Find Nearby demo", pillar: "Kenyan Driving Reality", format: "Skit", platforms: ["TikTok","Instagram Reels","Facebook Reels","YouTube Shorts"], angle: "Relatable weekend road trip tension.", hook: "POV: you are on the highway and nobody can agree on where to stop next.", captionSeed: "Every driver knows this argument. The smart move is having better information before the argument starts.", cta: "Tag the driver who does this.", status: "idea", isCore: false, founderMinutes: 25, notes: "Road trip skit." },
  { weekNumber: 6, scheduledDate: "2026-09-24", title: "Founder Files: Find Nearby demo", pillar: "Founder / BTS", format: "Founder-to-camera", platforms: ["Instagram Reels","TikTok","YouTube Shorts","LinkedIn"], angle: "Peter explains Find Nearby decision design.", hook: "Peter here — this is why Find Nearby in Msafiri is built around driver decisions, not just a list of places.", captionSeed: "The goal is not another app on your phone. The goal is a calmer, more prepared drive.", cta: "Follow Msafiri as we build for Kenyan roads.", status: "idea", isCore: true, founderMinutes: 45, notes: "Peter in car or office." },
  { weekNumber: 6, scheduledDate: "2026-09-25", title: "Road Mythbusters: Find Nearby demo", pillar: "Debate / Mythbusters", format: "Short-form video", platforms: ["TikTok","Instagram Reels","YouTube Shorts","Facebook Reels"], angle: "Debate: do map apps make Kenyan drivers too dependent?", hook: "Hot take: relying on map apps has made Kenyan drivers worse at navigating on their own.", captionSeed: "Debate is useful only if it makes us better drivers.", cta: "Agree or disagree?", status: "idea", isCore: false, founderMinutes: 25, notes: "Split screen, poll." },
  { weekNumber: 6, scheduledDate: "2026-09-26", title: "Road Safety KE: Find Nearby demo", pillar: "Education / Safety", format: "Explainer", platforms: ["Instagram Reels","TikTok","YouTube Shorts"], angle: "Explainer on safe highway stop planning.", hook: "Here is how to plan safe stops on a Kenya highway drive — and what to avoid.", captionSeed: "Knowing how the road works is the first step to driving it better.", cta: "Share this with someone planning a road trip.", status: "idea", isCore: false, founderMinutes: 30, notes: "On-screen text, safety context." },
  { weekNumber: 6, scheduledDate: "2026-09-27", title: "Before You Drive: Find Nearby demo", pillar: "Education / Safety", format: "Checklist Reel", platforms: ["Instagram Reels","TikTok","YouTube Shorts","Facebook Reels"], angle: "Weekend drive preparation checklist.", hook: "Save this weekend drives and nearby decisions checklist before your next road trip.", captionSeed: "A good drive often starts before the engine starts.", cta: "Save this.", status: "idea", isCore: false, founderMinutes: 20, notes: "Checklist overlay." },
  // Week 7: Group trips without confusion
  { weekNumber: 7, scheduledDate: "2026-09-28", title: "Msafiri Road Check: Trips / trip sharing demo", pillar: "Road Intelligence", format: "Hero / Reel", platforms: ["TikTok","Instagram Reels","YouTube Shorts","Facebook Reels","YouTube"], angle: "Planning a Nairobi-Nakuru group trip with Msafiri.", hook: "We planned a Nairobi-Nakuru highway group drive this week — here is what Msafiri kept everyone on the same page about.", captionSeed: "Road intelligence should feel practical, not complicated.", cta: "Tell us which road we should check next.", status: "idea", isCore: true, founderMinutes: 75, notes: "Highway road check, group trip demo." },
  { weekNumber: 7, scheduledDate: "2026-09-29", title: "Feature in the Wild: Trips / trip sharing demo", pillar: "Product / Feature Proof", format: "Short-form video", platforms: ["Instagram Reels","TikTok","YouTube Shorts","Facebook Reels"], angle: "Show trip sharing solving a real group decision moment.", hook: "Trips only makes sense when everyone in the group has a different plan; here is the 30-second version.", captionSeed: "A feature is only useful if it helps in the exact moment a driver needs it.", cta: "Try Msafiri on your next drive.", status: "idea", isCore: true, founderMinutes: 45, notes: "Screen-record, before/after." },
  { weekNumber: 7, scheduledDate: "2026-09-30", title: "Kenyan Driver Problems: Trips / trip sharing demo", pillar: "Kenyan Driving Reality", format: "Skit", platforms: ["TikTok","Instagram Reels","Facebook Reels","YouTube Shorts"], angle: "Relatable group trip chaos.", hook: "POV: four cars leaving Nairobi for Nakuru and nobody agrees on the meeting point.", captionSeed: "Every driver knows this argument.", cta: "Tag the driver who does this.", status: "idea", isCore: false, founderMinutes: 25, notes: "Group trip WhatsApp chaos skit." },
  { weekNumber: 7, scheduledDate: "2026-10-01", title: "Founder Files: Trips / trip sharing demo", pillar: "Founder / BTS", format: "Founder-to-camera", platforms: ["Instagram Reels","TikTok","YouTube Shorts","LinkedIn"], angle: "Peter explains the group trip coordination feature.", hook: "Peter here — this is why we built group trip features for Kenyan road trips.", captionSeed: "The goal is not another app on your phone. The goal is a calmer, more prepared drive.", cta: "Follow Msafiri as we build for Kenyan roads.", status: "idea", isCore: true, founderMinutes: 45, notes: "Peter on camera." },
  { weekNumber: 7, scheduledDate: "2026-10-02", title: "Road Mythbusters: Trips / trip sharing demo", pillar: "Debate / Mythbusters", format: "Short-form video", platforms: ["TikTok","Instagram Reels","YouTube Shorts","Facebook Reels"], angle: "Debate: convoy driving vs solo on Kenyan highways.", hook: "Hot take: convoy driving on Kenyan roads creates more hazards than it prevents.", captionSeed: "Debate is useful only if it makes us better drivers.", cta: "Agree or disagree?", status: "idea", isCore: false, founderMinutes: 25, notes: "Split screen, poll." },
  { weekNumber: 7, scheduledDate: "2026-10-03", title: "Road Safety KE: Trips / trip sharing demo", pillar: "Education / Safety", format: "Explainer", platforms: ["Instagram Reels","TikTok","YouTube Shorts"], angle: "Safe convoy and group trip guidance.", hook: "Here is how to run a safe convoy on a Kenyan highway — the rules most drivers skip.", captionSeed: "Knowing how the road works is the first step to driving it better.", cta: "Share this with your road trip group.", status: "idea", isCore: false, founderMinutes: 30, notes: "On-screen text, safety guidance." },
  { weekNumber: 7, scheduledDate: "2026-10-04", title: "Before You Drive: Trips / trip sharing demo", pillar: "Education / Safety", format: "Checklist Reel", platforms: ["Instagram Reels","TikTok","YouTube Shorts","Facebook Reels"], angle: "Group trips without confusion checklist.", hook: "Save this group trips without confusion checklist before your next convoy.", captionSeed: "A good drive often starts before the engine starts.", cta: "Save this.", status: "idea", isCore: false, founderMinutes: 20, notes: "Checklist overlay." },
  // Week 8: Culture, service and family-driving weekend
  { weekNumber: 8, scheduledDate: "2026-10-05", title: "Msafiri Road Check: Road alerts", pillar: "Road Intelligence", format: "Hero / Reel", platforms: ["TikTok","Instagram Reels","YouTube Shorts","Facebook Reels","YouTube"], angle: "City-to-family visit route check with Msafiri.", hook: "We drove city-to-family visit routes this week — here is what every family driver should know.", captionSeed: "Road intelligence should feel practical, not complicated.", cta: "Tell us which road we should check next.", status: "idea", isCore: true, founderMinutes: 75, notes: "POV drive, family route, road alerts demo." },
  { weekNumber: 8, scheduledDate: "2026-10-06", title: "Feature in the Wild: Road alerts", pillar: "Product / Feature Proof", format: "Short-form video", platforms: ["Instagram Reels","TikTok","YouTube Shorts","Facebook Reels"], angle: "Show road alerts on a family drive.", hook: "Road alerts only makes sense when you are carrying your family and do not know what is ahead.", captionSeed: "A feature is only useful if it helps in the exact moment a driver needs it.", cta: "Try Msafiri on your next drive.", status: "idea", isCore: true, founderMinutes: 45, notes: "Screen-record, before/after." },
  { weekNumber: 8, scheduledDate: "2026-10-07", title: "Kenyan Driver Problems: Road alerts", pillar: "Kenyan Driving Reality", format: "Skit", platforms: ["TikTok","Instagram Reels","Facebook Reels","YouTube Shorts"], angle: "Relatable family driving tension.", hook: "POV: driving upcountry with the family and you hit a diversion nobody warned you about.", captionSeed: "Every driver knows this argument.", cta: "Tag the driver who does this.", status: "idea", isCore: false, founderMinutes: 25, notes: "Family car skit." },
  { weekNumber: 8, scheduledDate: "2026-10-08", title: "Founder Files: Road alerts", pillar: "Founder / BTS", format: "Founder-to-camera", platforms: ["Instagram Reels","TikTok","YouTube Shorts","LinkedIn"], angle: "Peter explains how road alerts are sourced and verified.", hook: "Peter here — this is how Msafiri road alerts are verified before they reach you.", captionSeed: "The goal is not another app on your phone. The goal is a calmer, more prepared drive.", cta: "Follow Msafiri as we build for Kenyan roads.", status: "idea", isCore: true, founderMinutes: 45, notes: "Peter on camera, verification flow." },
  { weekNumber: 8, scheduledDate: "2026-10-09", title: "Road Mythbusters: Road alerts", pillar: "Debate / Mythbusters", format: "Short-form video", platforms: ["TikTok","Instagram Reels","YouTube Shorts","Facebook Reels"], angle: "Debate: family drivers vs solo drivers on Kenyan roads.", hook: "Hot take: family drives in Kenya are more stressful than driving solo on a busy highway.", captionSeed: "Debate is useful only if it makes us better drivers.", cta: "Agree or disagree?", status: "idea", isCore: false, founderMinutes: 25, notes: "Split screen, poll." },
  { weekNumber: 8, scheduledDate: "2026-10-10", title: "Road Safety KE: Road alerts", pillar: "Education / Safety", format: "Explainer", platforms: ["Instagram Reels","TikTok","YouTube Shorts"], angle: "Family road safety explainer.", hook: "Here is what every family driver in Kenya should check before a long drive — especially with children in the car.", captionSeed: "Knowing how the road works is the first step to driving it better.", cta: "Share this with a family driver you know.", status: "idea", isCore: false, founderMinutes: 30, notes: "On-screen text, family safety context." },
  { weekNumber: 8, scheduledDate: "2026-10-11", title: "Before You Drive: Road alerts", pillar: "Education / Safety", format: "Checklist Reel", platforms: ["Instagram Reels","TikTok","YouTube Shorts","Facebook Reels"], angle: "Culture, service and family-driving checklist.", hook: "Save this culture, service and family-driving weekend checklist before your next family drive.", captionSeed: "A good drive often starts before the engine starts.", cta: "Save this.", status: "idea", isCore: false, founderMinutes: 20, notes: "Checklist overlay." },
  // Week 9: Speed discipline and daily pressure
  { weekNumber: 9, scheduledDate: "2026-10-12", title: "Msafiri Road Check: Speed camera alerts demo", pillar: "Road Intelligence", format: "Hero / Reel", platforms: ["TikTok","Instagram Reels","YouTube Shorts","Facebook Reels","YouTube"], angle: "School run and work commute speed discipline.", hook: "We drove the school run / work commute route this week — here is the real speed pressure Nairobi drivers face.", captionSeed: "Road intelligence should feel practical, not complicated.", cta: "Tell us which road we should check next.", status: "idea", isCore: true, founderMinutes: 75, notes: "POV school run + commute, speed camera demo." },
  { weekNumber: 9, scheduledDate: "2026-10-13", title: "Feature in the Wild: Speed camera alerts demo", pillar: "Product / Feature Proof", format: "Short-form video", platforms: ["Instagram Reels","TikTok","YouTube Shorts","Facebook Reels"], angle: "Show speed alerts on a real commute.", hook: "Speed camera alerts only makes sense in the rush of a real commute; here is the 30-second version.", captionSeed: "A feature is only useful if it helps in the exact moment a driver needs it.", cta: "Try Msafiri on your next drive.", status: "idea", isCore: true, founderMinutes: 45, notes: "Screen-record, commute scenario." },
  { weekNumber: 9, scheduledDate: "2026-10-14", title: "Kenyan Driver Problems: Speed camera alerts demo", pillar: "Kenyan Driving Reality", format: "Skit", platforms: ["TikTok","Instagram Reels","Facebook Reels","YouTube Shorts"], angle: "The pressure to speed during the school run.", hook: "POV: you are running five minutes late to school drop-off and the speed camera is right there.", captionSeed: "Every driver knows this argument.", cta: "Tag the driver who does this.", status: "idea", isCore: false, founderMinutes: 25, notes: "School run skit, relatable Nairobi commute pressure." },
  { weekNumber: 9, scheduledDate: "2026-10-15", title: "Founder Files: Speed camera alerts demo", pillar: "Founder / BTS", format: "Founder-to-camera", platforms: ["Instagram Reels","TikTok","YouTube Shorts","LinkedIn"], angle: "Peter explains how Msafiri handles speed zone data.", hook: "Peter here — this is how Msafiri's speed zone data is collected and why it matters more than you think.", captionSeed: "The goal is not another app on your phone. The goal is a calmer, more prepared drive.", cta: "Follow Msafiri as we build for Kenyan roads.", status: "idea", isCore: true, founderMinutes: 45, notes: "Peter on camera, speed data context." },
  { weekNumber: 9, scheduledDate: "2026-10-16", title: "Road Mythbusters: Speed camera alerts demo", pillar: "Debate / Mythbusters", format: "Short-form video", platforms: ["TikTok","Instagram Reels","YouTube Shorts","Facebook Reels"], angle: "Debate: speed cameras — revenue trap or genuine safety?", hook: "Hot take: speed cameras in Kenya are about revenue, not about road safety.", captionSeed: "Debate is useful only if it makes us better drivers.", cta: "Agree or disagree?", status: "idea", isCore: false, founderMinutes: 25, notes: "Split screen, responsible closing." },
  { weekNumber: 9, scheduledDate: "2026-10-17", title: "Road Safety KE: Speed camera alerts demo", pillar: "Education / Safety", format: "Explainer", platforms: ["Instagram Reels","TikTok","YouTube Shorts"], angle: "Speed zone explainer for Nairobi drivers.", hook: "Here is how Kenyan speed zones work legally — and why the limits are where they are.", captionSeed: "Knowing how the road works is the first step to driving it better.", cta: "Share this with someone who drives the school run.", status: "idea", isCore: false, founderMinutes: 30, notes: "On-screen text, legal context." },
  { weekNumber: 9, scheduledDate: "2026-10-18", title: "Before You Drive: Speed camera alerts demo", pillar: "Education / Safety", format: "Checklist Reel", platforms: ["Instagram Reels","TikTok","YouTube Shorts","Facebook Reels"], angle: "Speed discipline checklist for daily drivers.", hook: "Save this speed discipline and daily pressure checklist before your next commute.", captionSeed: "A good drive often starts before the engine starts.", cta: "Save this.", status: "idea", isCore: false, founderMinutes: 20, notes: "Checklist overlay." },
  // Week 10: Mashujaa road heroes
  { weekNumber: 10, scheduledDate: "2026-10-19", title: "Msafiri Road Check: Accident Assistant demo", pillar: "Road Intelligence", format: "Hero / Reel", platforms: ["TikTok","Instagram Reels","YouTube Shorts","Facebook Reels","YouTube"], angle: "Mashujaa Day travel window road check.", hook: "We drove the Mashujaa Day travel corridor this week — here is what drivers should know before the holiday weekend.", captionSeed: "Road intelligence should feel practical, not complicated.", cta: "Tell us which road we should check next.", status: "idea", isCore: true, founderMinutes: 75, notes: "POV holiday corridor, Accident Assistant demo." },
  { weekNumber: 10, scheduledDate: "2026-10-20", title: "Feature in the Wild: Accident Assistant demo", pillar: "Product / Feature Proof", format: "Short-form video", platforms: ["Instagram Reels","TikTok","YouTube Shorts","Facebook Reels"], angle: "Show Accident Assistant on a holiday drive scenario.", hook: "Accident Assistant only makes sense when the holiday roads are busiest; here is the 30-second version.", captionSeed: "A feature is only useful if it helps in the exact moment a driver needs it.", cta: "Try Msafiri on your next drive.", status: "idea", isCore: true, founderMinutes: 45, notes: "Screen-record, holiday scenario." },
  { weekNumber: 10, scheduledDate: "2026-10-21", title: "Kenyan Driver Problems: Accident Assistant demo", pillar: "Kenyan Driving Reality", format: "Skit", platforms: ["TikTok","Instagram Reels","Facebook Reels","YouTube Shorts"], angle: "Relatable holiday drive overconfidence.", hook: "POV: Mashujaa Day weekend, everyone is a road hero until the traffic hits.", captionSeed: "Every driver knows this argument.", cta: "Tag the driver who does this.", status: "idea", isCore: false, founderMinutes: 25, notes: "Holiday drive skit." },
  { weekNumber: 10, scheduledDate: "2026-10-22", title: "Founder Files: Accident Assistant demo", pillar: "Founder / BTS", format: "Founder-to-camera", platforms: ["Instagram Reels","TikTok","YouTube Shorts","LinkedIn"], angle: "Peter explains Accident Assistant for holiday driving.", hook: "Peter here — this is why Accident Assistant matters most on Kenyan holiday weekends.", captionSeed: "The goal is not another app on your phone. The goal is a calmer, more prepared drive.", cta: "Follow Msafiri as we build for Kenyan roads.", status: "idea", isCore: true, founderMinutes: 45, notes: "Peter on camera, holiday context." },
  { weekNumber: 10, scheduledDate: "2026-10-23", title: "Road Mythbusters: Accident Assistant demo", pillar: "Debate / Mythbusters", format: "Short-form video", platforms: ["TikTok","Instagram Reels","YouTube Shorts","Facebook Reels"], angle: "Debate: are Kenyan holiday drivers more reckless?", hook: "Hot take: Kenyan drivers are measurably worse on long-weekend roads than on regular days.", captionSeed: "Debate is useful only if it makes us better drivers.", cta: "Agree or disagree?", status: "idea", isCore: false, founderMinutes: 25, notes: "Split screen, responsible closing." },
  { weekNumber: 10, scheduledDate: "2026-10-24", title: "Road Safety KE: Accident Assistant demo", pillar: "Education / Safety", format: "Explainer", platforms: ["Instagram Reels","TikTok","YouTube Shorts"], angle: "Mashujaa holiday driving safety explainer.", hook: "Here is how to drive the Mashujaa holiday roads safely — and what most drivers skip.", captionSeed: "Knowing how the road works is the first step to driving it better.", cta: "Share this before the holiday weekend.", status: "idea", isCore: false, founderMinutes: 30, notes: "Holiday safety context." },
  { weekNumber: 10, scheduledDate: "2026-10-25", title: "Before You Drive: Accident Assistant demo", pillar: "Education / Safety", format: "Checklist Reel", platforms: ["Instagram Reels","TikTok","YouTube Shorts","Facebook Reels"], angle: "Mashujaa road heroes checklist.", hook: "Save this Mashujaa road heroes checklist before your holiday drive.", captionSeed: "A good drive often starts before the engine starts.", cta: "Save this.", status: "idea", isCore: false, founderMinutes: 20, notes: "Checklist overlay." },
  // Weeks 11-20: condensed to core 4 posts each for brevity
  { weekNumber: 11, scheduledDate: "2026-10-26", title: "Msafiri Road Check: Community road intelligence demo", pillar: "Road Intelligence", format: "Hero / Reel", platforms: ["TikTok","Instagram Reels","YouTube Shorts","Facebook Reels","YouTube"], angle: "Kenyan driving myths vs reality road check.", hook: "We drove bypass vs city-road comparisons this week — here is what the community road intelligence shows.", captionSeed: "Road intelligence should feel practical, not complicated.", cta: "Tell us which road we should check next.", status: "idea", isCore: true, founderMinutes: 75, notes: "POV bypass + city comparison, community reports demo." },
  { weekNumber: 11, scheduledDate: "2026-10-27", title: "Feature in the Wild: Community road intelligence demo", pillar: "Product / Feature Proof", format: "Short-form video", platforms: ["Instagram Reels","TikTok","YouTube Shorts","Facebook Reels"], angle: "Show community reports solving a real driving decision.", hook: "Community road intelligence only makes sense when you need to trust the road, not just the app; here is the 30-second version.", captionSeed: "A feature is only useful if it helps in the exact moment a driver needs it.", cta: "Try Msafiri on your next drive.", status: "idea", isCore: true, founderMinutes: 45, notes: "Screen-record, community report demo." },
  { weekNumber: 11, scheduledDate: "2026-10-28", title: "Kenyan Driver Problems: Community road intelligence demo", pillar: "Kenyan Driving Reality", format: "Skit", platforms: ["TikTok","Instagram Reels","Facebook Reels","YouTube Shorts"], angle: "Relatable driving myth moment.", hook: "POV: everyone knows the bypass is faster until it isn't.", captionSeed: "Every driver knows this argument.", cta: "Tag the driver who does this.", status: "idea", isCore: false, founderMinutes: 25, notes: "Bypass vs city road skit." },
  { weekNumber: 11, scheduledDate: "2026-10-29", title: "Founder Files: Community road intelligence demo", pillar: "Founder / BTS", format: "Founder-to-camera", platforms: ["Instagram Reels","TikTok","YouTube Shorts","LinkedIn"], angle: "Peter explains how community data is verified.", hook: "Peter here — this is how community road intelligence is verified before it reaches your screen.", captionSeed: "The goal is not another app on your phone. The goal is a calmer, more prepared drive.", cta: "Follow Msafiri as we build for Kenyan roads.", status: "idea", isCore: true, founderMinutes: 45, notes: "Peter on camera, verification process." },
  { weekNumber: 12, scheduledDate: "2026-11-02", title: "Msafiri Road Check: Insurance-ready reports demo", pillar: "Road Intelligence", format: "Hero / Reel", platforms: ["TikTok","Instagram Reels","YouTube Shorts","Facebook Reels","YouTube"], angle: "Insurance evidence road check near parking lots.", hook: "We drove parking lots / low-speed incident examples this week — here is what your insurer needs that most drivers miss.", captionSeed: "Road intelligence should feel practical, not complicated.", cta: "Tell us which road we should check next.", status: "idea", isCore: true, founderMinutes: 75, notes: "Parking lot demo, insurance report feature." },
  { weekNumber: 12, scheduledDate: "2026-11-03", title: "Feature in the Wild: Insurance-ready reports demo", pillar: "Product / Feature Proof", format: "Short-form video", platforms: ["Instagram Reels","TikTok","YouTube Shorts","Facebook Reels"], angle: "Show insurance reports solving a real post-incident moment.", hook: "Insurance-ready reports only makes sense when the incident happened and everyone is scrambling; here is the 30-second version.", captionSeed: "A feature is only useful if it helps in the exact moment a driver needs it.", cta: "Try Msafiri on your next drive.", status: "idea", isCore: true, founderMinutes: 45, notes: "Screen-record, incident report flow." },
  { weekNumber: 12, scheduledDate: "2026-11-04", title: "Kenyan Driver Problems: Insurance-ready reports demo", pillar: "Kenyan Driving Reality", format: "Skit", platforms: ["TikTok","Instagram Reels","Facebook Reels","YouTube Shorts"], angle: "The relatable insurance claim confusion.", hook: "POV: you have a minor incident and your insurer asks for documents you have never heard of.", captionSeed: "Every driver knows this argument.", cta: "Tag the driver who does this.", status: "idea", isCore: false, founderMinutes: 25, notes: "Insurance claim skit." },
  { weekNumber: 12, scheduledDate: "2026-11-05", title: "Founder Files: Insurance-ready reports demo", pillar: "Founder / BTS", format: "Founder-to-camera", platforms: ["Instagram Reels","TikTok","YouTube Shorts","LinkedIn"], angle: "Peter explains the insurance evidence feature.", hook: "Peter here — this is why we built insurance-ready reports directly into a driving app.", captionSeed: "The goal is not another app on your phone. The goal is a calmer, more prepared drive.", cta: "Follow Msafiri as we build for Kenyan roads.", status: "idea", isCore: true, founderMinutes: 45, notes: "Peter on camera." },
  { weekNumber: 13, scheduledDate: "2026-11-09", title: "Msafiri Road Check: Community road intelligence demo", pillar: "Road Intelligence", format: "Hero / Reel", platforms: ["TikTok","Instagram Reels","YouTube Shorts","Facebook Reels","YouTube"], angle: "Community-nominated road check.", hook: "You told us which road to check — we drove it and here is what the community intelligence showed.", captionSeed: "Road intelligence should feel practical, not complicated.", cta: "Tell us which road we should check next.", status: "idea", isCore: true, founderMinutes: 75, notes: "Audience-nominated road, community reports demo." },
  { weekNumber: 13, scheduledDate: "2026-11-10", title: "Feature in the Wild: Community road intelligence demo", pillar: "Product / Feature Proof", format: "Short-form video", platforms: ["Instagram Reels","TikTok","YouTube Shorts","Facebook Reels"], angle: "Show community road intelligence on an audience-requested route.", hook: "Community road intelligence only makes sense when you trust the people driving the same road; here is the 30-second version.", captionSeed: "A feature is only useful if it helps in the exact moment a driver needs it.", cta: "Try Msafiri on your next drive.", status: "idea", isCore: true, founderMinutes: 45, notes: "Screen-record, community data." },
  { weekNumber: 13, scheduledDate: "2026-11-11", title: "Kenyan Driver Problems: Community road intelligence demo", pillar: "Kenyan Driving Reality", format: "Skit", platforms: ["TikTok","Instagram Reels","Facebook Reels","YouTube Shorts"], angle: "Relatable community knowledge vs gossip tension.", hook: "POV: you got road advice from your WhatsApp group and it was completely wrong.", captionSeed: "Every driver knows this argument.", cta: "Tag the driver who does this.", status: "idea", isCore: false, founderMinutes: 25, notes: "WhatsApp group road advice skit." },
  { weekNumber: 13, scheduledDate: "2026-11-12", title: "Founder Files: Community road intelligence demo", pillar: "Founder / BTS", format: "Founder-to-camera", platforms: ["Instagram Reels","TikTok","YouTube Shorts","LinkedIn"], angle: "Peter explains how the community road check engine works.", hook: "Peter here — this is how Msafiri turns community reports into verified road intelligence.", captionSeed: "The goal is not another app on your phone. The goal is a calmer, more prepared drive.", cta: "Follow Msafiri as we build for Kenyan roads.", status: "idea", isCore: true, founderMinutes: 45, notes: "Peter on camera, verification flow." },
  { weekNumber: 14, scheduledDate: "2026-11-16", title: "Msafiri Road Check: Built-in Dashcam demo", pillar: "Road Intelligence", format: "Hero / Reel", platforms: ["TikTok","Instagram Reels","YouTube Shorts","Facebook Reels","YouTube"], angle: "Night, rain and low-visibility road check.", hook: "We drove a night commute / rainy-day city drive this week — here is what the dashcam captured that mattered.", captionSeed: "Road intelligence should feel practical, not complicated.", cta: "Tell us which road we should check next.", status: "idea", isCore: true, founderMinutes: 75, notes: "Night drive + dashcam, low-visibility demo." },
  { weekNumber: 14, scheduledDate: "2026-11-17", title: "Feature in the Wild: Built-in Dashcam demo", pillar: "Product / Feature Proof", format: "Short-form video", platforms: ["Instagram Reels","TikTok","YouTube Shorts","Facebook Reels"], angle: "Show dashcam recording on a night drive.", hook: "Built-in Dashcam only makes sense when visibility is low and the road is unpredictable; here is the 30-second version.", captionSeed: "A feature is only useful if it helps in the exact moment a driver needs it.", cta: "Try Msafiri on your next drive.", status: "idea", isCore: true, founderMinutes: 45, notes: "Night driving screen-record, dashcam footage." },
  { weekNumber: 14, scheduledDate: "2026-11-18", title: "Kenyan Driver Problems: Built-in Dashcam demo", pillar: "Kenyan Driving Reality", format: "Skit", platforms: ["TikTok","Instagram Reels","Facebook Reels","YouTube Shorts"], angle: "Relatable night driving tension.", hook: "POV: it starts raining at 7pm on Ngong Road and nobody's lights are working properly.", captionSeed: "Every driver knows this argument.", cta: "Tag the driver who does this.", status: "idea", isCore: false, founderMinutes: 25, notes: "Night rain skit." },
  { weekNumber: 14, scheduledDate: "2026-11-19", title: "Founder Files: Built-in Dashcam demo", pillar: "Founder / BTS", format: "Founder-to-camera", platforms: ["Instagram Reels","TikTok","YouTube Shorts","LinkedIn"], angle: "Peter explains night and rain driving decisions in Msafiri.", hook: "Peter here — this is why night and rain detection matters for a Kenyan road-safety app.", captionSeed: "The goal is not another app on your phone. The goal is a calmer, more prepared drive.", cta: "Follow Msafiri as we build for Kenyan roads.", status: "idea", isCore: true, founderMinutes: 45, notes: "Peter on camera, night driving context." },
  { weekNumber: 15, scheduledDate: "2026-11-23", title: "Msafiri Road Check: Msafiri brand trust demo", pillar: "Road Intelligence", format: "Hero / Reel", platforms: ["TikTok","Instagram Reels","YouTube Shorts","Facebook Reels","YouTube"], angle: "Build-in-public trust road check.", hook: "This week we drove the office, car and road-test loop — and here is the build-in-public story behind the road check.", captionSeed: "Road intelligence should feel practical, not complicated.", cta: "Tell us which road we should check next.", status: "idea", isCore: true, founderMinutes: 75, notes: "Office + road test loop, founder transparency." },
  { weekNumber: 15, scheduledDate: "2026-11-24", title: "Feature in the Wild: Msafiri brand trust demo", pillar: "Product / Feature Proof", format: "Short-form video", platforms: ["Instagram Reels","TikTok","YouTube Shorts","Facebook Reels"], angle: "Show Msafiri in a real trust-building moment.", hook: "Msafiri brand trust only makes sense when you show how the product is actually built; here is the 30-second version.", captionSeed: "A feature is only useful if it helps in the exact moment a driver needs it.", cta: "Try Msafiri on your next drive.", status: "idea", isCore: true, founderMinutes: 45, notes: "Build-in-public screen-record." },
  { weekNumber: 15, scheduledDate: "2026-11-25", title: "Kenyan Driver Problems: Msafiri brand trust demo", pillar: "Kenyan Driving Reality", format: "Skit", platforms: ["TikTok","Instagram Reels","Facebook Reels","YouTube Shorts"], angle: "Relatable scepticism about road apps.", hook: "POV: someone tells you to trust a Kenyan road app and you have never heard of it.", captionSeed: "Every driver knows this argument.", cta: "Tag the driver who does this.", status: "idea", isCore: false, founderMinutes: 25, notes: "App scepticism skit." },
  { weekNumber: 15, scheduledDate: "2026-11-26", title: "Founder Files: Msafiri brand trust demo", pillar: "Founder / BTS", format: "Founder-to-camera", platforms: ["Instagram Reels","TikTok","YouTube Shorts","LinkedIn"], angle: "Peter's build-in-public story.", hook: "Peter here — this is the real build-in-public story behind Msafiri Kenya.", captionSeed: "The goal is not another app on your phone. The goal is a calmer, more prepared drive.", cta: "Follow Msafiri as we build for Kenyan roads.", status: "idea", isCore: true, founderMinutes: 45, notes: "Peter on camera, founder story." },
  { weekNumber: 16, scheduledDate: "2026-11-30", title: "Msafiri Road Check: Trips / trip sharing demo", pillar: "Road Intelligence", format: "Hero / Reel", platforms: ["TikTok","Instagram Reels","YouTube Shorts","Facebook Reels","YouTube"], angle: "December travel countdown road check.", hook: "We drove upcountry travel preparation routes this week — here is what every December traveller should know.", captionSeed: "Road intelligence should feel practical, not complicated.", cta: "Tell us which road we should check next.", status: "idea", isCore: true, founderMinutes: 75, notes: "Upcountry prep, trip planning demo." },
  { weekNumber: 16, scheduledDate: "2026-12-01", title: "Feature in the Wild: Trips / trip sharing demo", pillar: "Product / Feature Proof", format: "Short-form video", platforms: ["Instagram Reels","TikTok","YouTube Shorts","Facebook Reels"], angle: "December travel trip planning with Msafiri.", hook: "Trips only makes sense when December travel is real and everyone needs to coordinate; here is the 30-second version.", captionSeed: "A feature is only useful if it helps in the exact moment a driver needs it.", cta: "Try Msafiri on your next drive.", status: "idea", isCore: true, founderMinutes: 45, notes: "Screen-record, December travel planning." },
  { weekNumber: 16, scheduledDate: "2026-12-02", title: "Kenyan Driver Problems: Trips / trip sharing demo", pillar: "Kenyan Driving Reality", format: "Skit", platforms: ["TikTok","Instagram Reels","Facebook Reels","YouTube Shorts"], angle: "December travel stress skit.", hook: "POV: it is December 19th and your whole family has a different plan for the trip home.", captionSeed: "Every driver knows this argument.", cta: "Tag the driver who does this.", status: "idea", isCore: false, founderMinutes: 25, notes: "December travel chaos skit." },
  { weekNumber: 16, scheduledDate: "2026-12-03", title: "Founder Files: Trips / trip sharing demo", pillar: "Founder / BTS", format: "Founder-to-camera", platforms: ["Instagram Reels","TikTok","YouTube Shorts","LinkedIn"], angle: "Peter explains December road preparation.", hook: "Peter here — this is how Msafiri helps you prepare for the December driving season.", captionSeed: "The goal is not another app on your phone. The goal is a calmer, more prepared drive.", cta: "Follow Msafiri as we build for Kenyan roads.", status: "idea", isCore: true, founderMinutes: 45, notes: "Peter on camera, December travel." },
  { weekNumber: 17, scheduledDate: "2026-12-07", title: "Msafiri Road Check: Road alerts demo", pillar: "Road Intelligence", format: "Hero / Reel", platforms: ["TikTok","Instagram Reels","YouTube Shorts","Facebook Reels","YouTube"], angle: "Jamhuri long-drive road check.", hook: "We drove Jamhuri Day weekend routes this week — here is what every driver should know before the long weekend.", captionSeed: "Road intelligence should feel practical, not complicated.", cta: "Tell us which road we should check next.", status: "idea", isCore: true, founderMinutes: 75, notes: "Jamhuri road check, alerts demo." },
  { weekNumber: 17, scheduledDate: "2026-12-08", title: "Feature in the Wild: Road alerts demo", pillar: "Product / Feature Proof", format: "Short-form video", platforms: ["Instagram Reels","TikTok","YouTube Shorts","Facebook Reels"], angle: "Show road alerts on a Jamhuri long drive.", hook: "Road alerts only makes sense when the long-weekend roads are the most unpredictable; here is the 30-second version.", captionSeed: "A feature is only useful if it helps in the exact moment a driver needs it.", cta: "Try Msafiri on your next drive.", status: "idea", isCore: true, founderMinutes: 45, notes: "Screen-record, Jamhuri drive scenario." },
  { weekNumber: 17, scheduledDate: "2026-12-09", title: "Kenyan Driver Problems: Road alerts demo", pillar: "Kenyan Driving Reality", format: "Skit", platforms: ["TikTok","Instagram Reels","Facebook Reels","YouTube Shorts"], angle: "Jamhuri holiday overconfidence skit.", hook: "POV: Jamhuri weekend, everyone leaves Nairobi at the same time and acts surprised by traffic.", captionSeed: "Every driver knows this argument.", cta: "Tag the driver who does this.", status: "idea", isCore: false, founderMinutes: 25, notes: "Jamhuri traffic skit." },
  { weekNumber: 17, scheduledDate: "2026-12-10", title: "Founder Files: Road alerts demo", pillar: "Founder / BTS", format: "Founder-to-camera", platforms: ["Instagram Reels","TikTok","YouTube Shorts","LinkedIn"], angle: "Peter explains Jamhuri driving preparation.", hook: "Peter here — this is how Msafiri prepares drivers for the Jamhuri long-drive season.", captionSeed: "The goal is not another app on your phone. The goal is a calmer, more prepared drive.", cta: "Follow Msafiri as we build for Kenyan roads.", status: "idea", isCore: true, founderMinutes: 45, notes: "Peter on camera, Jamhuri context." },
  { weekNumber: 18, scheduledDate: "2026-12-14", title: "Msafiri Road Check: Find Nearby demo", pillar: "Road Intelligence", format: "Hero / Reel", platforms: ["TikTok","Instagram Reels","YouTube Shorts","Facebook Reels","YouTube"], angle: "End-year road-trip confidence road check.", hook: "We drove coast/upcountry route planning this week — here is the road trip prep every December driver needs.", captionSeed: "Road intelligence should feel practical, not complicated.", cta: "Tell us which road we should check next.", status: "idea", isCore: true, founderMinutes: 75, notes: "End-year road trip, Find Nearby demo." },
  { weekNumber: 18, scheduledDate: "2026-12-15", title: "Feature in the Wild: Find Nearby demo", pillar: "Product / Feature Proof", format: "Short-form video", platforms: ["Instagram Reels","TikTok","YouTube Shorts","Facebook Reels"], angle: "Show Find Nearby on an end-year road trip.", hook: "Find Nearby only makes sense when the road trip is real and you need a reliable decision fast.", captionSeed: "A feature is only useful if it helps in the exact moment a driver needs it.", cta: "Try Msafiri on your next drive.", status: "idea", isCore: true, founderMinutes: 45, notes: "Screen-record, end-year trip planning." },
  { weekNumber: 18, scheduledDate: "2026-12-16", title: "Kenyan Driver Problems: Find Nearby demo", pillar: "Kenyan Driving Reality", format: "Skit", platforms: ["TikTok","Instagram Reels","Facebook Reels","YouTube Shorts"], angle: "End-year road trip confusion skit.", hook: "POV: you are on the Nairobi-Mombasa highway and the next stop is 80km away according to one person and 15km according to another.", captionSeed: "Every driver knows this argument.", cta: "Tag the driver who does this.", status: "idea", isCore: false, founderMinutes: 25, notes: "Road trip confusion skit." },
  { weekNumber: 18, scheduledDate: "2026-12-17", title: "Founder Files: Find Nearby demo", pillar: "Founder / BTS", format: "Founder-to-camera", platforms: ["Instagram Reels","TikTok","YouTube Shorts","LinkedIn"], angle: "Peter explains end-year road confidence.", hook: "Peter here — this is how Msafiri helps drivers be confident on the end-year long road.", captionSeed: "The goal is not another app on your phone. The goal is a calmer, more prepared drive.", cta: "Follow Msafiri as we build for Kenyan roads.", status: "idea", isCore: true, founderMinutes: 45, notes: "Peter on camera." },
  { weekNumber: 19, scheduledDate: "2026-12-21", title: "Msafiri Road Check: Accident Assistant demo", pillar: "Road Intelligence", format: "Hero / Reel", platforms: ["TikTok","Instagram Reels","YouTube Shorts","Facebook Reels","YouTube"], angle: "Christmas week arrival safety road check.", hook: "We drove the Christmas travel window routes this week — here is what every driver heading home should know.", captionSeed: "Road intelligence should feel practical, not complicated.", cta: "Tell us which road we should check next.", status: "idea", isCore: true, founderMinutes: 75, notes: "Christmas travel window, Accident Assistant demo." },
  { weekNumber: 19, scheduledDate: "2026-12-22", title: "Feature in the Wild: Accident Assistant demo", pillar: "Product / Feature Proof", format: "Short-form video", platforms: ["Instagram Reels","TikTok","YouTube Shorts","Facebook Reels"], angle: "Show Accident Assistant on a Christmas road trip.", hook: "Accident Assistant only makes sense when the Christmas roads are the most crowded and mistakes happen; here is the 30-second version.", captionSeed: "A feature is only useful if it helps in the exact moment a driver needs it.", cta: "Try Msafiri on your next drive.", status: "idea", isCore: true, founderMinutes: 45, notes: "Screen-record, Christmas scenario." },
  { weekNumber: 19, scheduledDate: "2026-12-23", title: "Kenyan Driver Problems: Accident Assistant demo", pillar: "Kenyan Driving Reality", format: "Skit", platforms: ["TikTok","Instagram Reels","Facebook Reels","YouTube Shorts"], angle: "Christmas arrival overconfidence skit.", hook: "POV: it is Christmas Eve, everyone is 'almost home' and nobody is actually watching the road.", captionSeed: "Every driver knows this argument.", cta: "Tag the driver who does this.", status: "idea", isCore: false, founderMinutes: 25, notes: "Christmas drive skit." },
  { weekNumber: 19, scheduledDate: "2026-12-24", title: "Founder Files: Accident Assistant demo", pillar: "Founder / BTS", format: "Founder-to-camera", platforms: ["Instagram Reels","TikTok","YouTube Shorts","LinkedIn"], angle: "Peter's Christmas road safety message.", hook: "Peter here — here is why Christmas road safety is the most important week for Msafiri.", captionSeed: "The goal is not another app on your phone. The goal is a calmer, more prepared drive.", cta: "Follow Msafiri as we build for Kenyan roads.", status: "idea", isCore: true, founderMinutes: 45, notes: "Peter on camera, Christmas context." },
  { weekNumber: 20, scheduledDate: "2026-12-28", title: "Msafiri Road Check: Alcoblow / sober-driving reminders demo", pillar: "Road Intelligence", format: "Hero / Reel", platforms: ["TikTok","Instagram Reels","YouTube Shorts","Facebook Reels","YouTube"], angle: "Year-end recap and sober-driving road check.", hook: "We drove the New Year travel window routes this week — here is what every driver should know about sober driving season.", captionSeed: "Road intelligence should feel practical, not complicated.", cta: "Tell us which road we should check next.", status: "idea", isCore: true, founderMinutes: 75, notes: "New Year window, sober driving demo." },
  { weekNumber: 20, scheduledDate: "2026-12-29", title: "Feature in the Wild: Alcoblow / sober-driving reminders demo", pillar: "Product / Feature Proof", format: "Short-form video", platforms: ["Instagram Reels","TikTok","YouTube Shorts","Facebook Reels"], angle: "Show sober driving features in a New Year context.", hook: "Sober driving reminders only matters when the New Year roads have the highest risk; here is the 30-second version.", captionSeed: "A feature is only useful if it helps in the exact moment a driver needs it.", cta: "Try Msafiri on your next drive.", status: "idea", isCore: true, founderMinutes: 45, notes: "Screen-record, New Year scenario." },
  { weekNumber: 20, scheduledDate: "2026-12-30", title: "Kenyan Driver Problems: Alcoblow / sober-driving reminders demo", pillar: "Kenyan Driving Reality", format: "Skit", platforms: ["TikTok","Instagram Reels","Facebook Reels","YouTube Shorts"], angle: "New Year's Eve driving decisions skit.", hook: "POV: New Year's Eve and someone in the group says they're 'fine to drive'.", captionSeed: "Every driver knows this argument.", cta: "Tag the driver who does this.", status: "idea", isCore: false, founderMinutes: 25, notes: "New Year's Eve sober driving skit." },
  { weekNumber: 20, scheduledDate: "2026-12-31", title: "Founder Files: Alcoblow / sober-driving reminders demo", pillar: "Founder / BTS", format: "Founder-to-camera", platforms: ["Instagram Reels","TikTok","YouTube Shorts","LinkedIn"], angle: "Peter's year-end road safety and sober driving message.", hook: "Peter here — here is our year-end road safety commitment and what Msafiri stands for.", captionSeed: "The goal is not another app on your phone. The goal is a calmer, more prepared drive.", cta: "Follow Msafiri as we build for Kenyan roads.", status: "idea", isCore: true, founderMinutes: 45, notes: "Peter on camera, year-end reflection." },
];

export async function seedOpsData(logger: Logger) {
  const label = "seedOpsData";

  // ── 1. Operating weeks — idempotent by weekNumber ─────────────────────────
  let weekIdByNumber: Record<number, number> = {};

  const existingWeeks = await db
    .select({ id: opsOperatingWeeksTable.id, weekNumber: opsOperatingWeeksTable.weekNumber })
    .from(opsOperatingWeeksTable);

  if (existingWeeks.length === 0) {
    logger.info(`${label}: seeding 24 operating weeks…`);
    const insertedWeeks = await db
      .insert(opsOperatingWeeksTable)
      .values(
        WEEKS.map((w) => ({
          weekNumber: w.weekNumber,
          startDate: w.startDate,
          endDate: w.endDate,
          plannedCashInKes: w.plannedCashIn,
          plannedCashOutKes: w.plannedCashOut,
        }))
      )
      .returning({ id: opsOperatingWeeksTable.id, weekNumber: opsOperatingWeeksTable.weekNumber });
    insertedWeeks.forEach((w) => { weekIdByNumber[w.weekNumber] = w.id; });
  } else {
    existingWeeks.forEach((w) => { weekIdByNumber[w.weekNumber] = w.id; });
    logger.info(`${label}: ${existingWeeks.length} weeks already exist — reusing`);
  }

  // ── 2. Weekly plans ───────────────────────────────────────────────────────
  const [existingPlan] = await db
    .select({ id: opsWeeklyPlansTable.id })
    .from(opsWeeklyPlansTable)
    .limit(1);

  if (!existingPlan) {
    logger.info(`${label}: seeding ${WEEKLY_PLANS.length} weekly plans…`);
    await db.insert(opsWeeklyPlansTable).values(
      WEEKLY_PLANS.map((p) => ({
        weekId: weekIdByNumber[p.weekNumber]!,
        mainObjective: p.mainObjective,
        requiredOutcomes: p.requiredOutcomes,
        cashDecision: p.cashDecision,
      }))
    );
  } else {
    logger.info(`${label}: weekly plans already exist — skipping`);
  }

  // ── 3. Transaction categories ─────────────────────────────────────────────
  let catIdByName: Record<string, number> = {};

  const existingCats = await db
    .select({ id: opsTransactionCategoriesTable.id, name: opsTransactionCategoriesTable.name })
    .from(opsTransactionCategoriesTable);

  if (existingCats.length === 0) {
    logger.info(`${label}: seeding ${CATEGORIES.length} transaction categories…`);
    const insertedCats = await db
      .insert(opsTransactionCategoriesTable)
      .values(CATEGORIES.map((c) => ({ name: c.name, type: c.type, description: c.description, isSystem: c.isSystem })))
      .returning({ id: opsTransactionCategoriesTable.id, name: opsTransactionCategoriesTable.name });
    insertedCats.forEach((c) => { catIdByName[c.name] = c.id; });
  } else {
    existingCats.forEach((c) => { catIdByName[c.name] = c.id; });
    logger.info(`${label}: ${existingCats.length} categories already exist — reusing`);
  }

  // ── 4. Recurring expenses ─────────────────────────────────────────────────
  const [existingRecurring] = await db
    .select({ id: opsRecurringExpensesTable.id })
    .from(opsRecurringExpensesTable)
    .limit(1);

  if (!existingRecurring) {
    logger.info(`${label}: seeding ${RECURRING_EXPENSES.length} recurring expenses…`);
    await db.insert(opsRecurringExpensesTable).values(
      RECURRING_EXPENSES.map((e) => ({
        name: e.name,
        amountKes: e.amountKes,
        amountUsd: e.amountUsd ?? undefined,
        currencyType: e.currencyType,
        frequency: e.frequency,
        categoryId: catIdByName[e.categoryName] ?? null,
        nextBillingDate: e.nextBillingDate,
        notes: e.notes,
        isActive: true,
      }))
    );
  } else {
    logger.info(`${label}: recurring expenses already exist — skipping`);
  }

  // ── 5. Ops settings ───────────────────────────────────────────────────────
  await db
    .insert(opsSettingsTable)
    .values({
      firstFundingDate: "2026-08-14",
      weeklyFundingAmountKes: "10000.00",
      cashFloorKes: "2500.00",
      reserveTransferTargetKes: "1500.00",
      replitMonthlyUsd: "20.00",
      replitNextBillingDate: "2026-08-14",
      exchangeRateKesPerUsd: "129.3600",
      fuelPricePerLitreKes: "214.00",
      vehicleEfficiencyKmPerLitre: "12.00",
    })
    .onConflictDoNothing();

  // ── 6. Content items ──────────────────────────────────────────────────────
  const [existingContent] = await db
    .select({ id: opsContentItemsTable.id })
    .from(opsContentItemsTable)
    .limit(1);

  if (!existingContent) {
    logger.info(`${label}: seeding ${CONTENT.length} content items…`);
    await db.insert(opsContentItemsTable).values(
      CONTENT.map((c) => ({
        title: c.title,
        status: c.status,
        weekId: weekIdByNumber[c.weekNumber] ?? null,
        isCore: c.isCore,
        platforms: c.platforms,
        pillar: c.pillar,
        format: c.format,
        angle: c.angle,
        hook: c.hook,
        captionSeed: c.captionSeed,
        cta: c.cta,
        scheduledDate: c.scheduledDate,
        founderMinutes: c.founderMinutes,
        notes: c.notes,
      }))
    );
  } else {
    logger.info(`${label}: content items already exist — skipping`);
  }

  logger.info(`${label}: done`);
}
